// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: manifest/v1/manifest.proto

package manifestv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManifestAPI_CreateManifest_FullMethodName = "/admiral.manifest.v1.ManifestAPI/CreateManifest"
	ManifestAPI_ListManifests_FullMethodName  = "/admiral.manifest.v1.ManifestAPI/ListManifests"
	ManifestAPI_GetManifest_FullMethodName    = "/admiral.manifest.v1.ManifestAPI/GetManifest"
	ManifestAPI_UpdateManifest_FullMethodName = "/admiral.manifest.v1.ManifestAPI/UpdateManifest"
	ManifestAPI_DeleteManifest_FullMethodName = "/admiral.manifest.v1.ManifestAPI/DeleteManifest"
)

// ManifestAPIClient is the client API for ManifestAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManifestAPIClient interface {
	CreateManifest(ctx context.Context, in *CreateManifestRequest, opts ...grpc.CallOption) (*CreateManifestResponse, error)
	ListManifests(ctx context.Context, in *ListManifestsRequest, opts ...grpc.CallOption) (*ListManifestsResponse, error)
	GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error)
	UpdateManifest(ctx context.Context, in *UpdateManifestRequest, opts ...grpc.CallOption) (*UpdateManifestResponse, error)
	DeleteManifest(ctx context.Context, in *DeleteManifestRequest, opts ...grpc.CallOption) (*DeleteManifestResponse, error)
}

type manifestAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewManifestAPIClient(cc grpc.ClientConnInterface) ManifestAPIClient {
	return &manifestAPIClient{cc}
}

func (c *manifestAPIClient) CreateManifest(ctx context.Context, in *CreateManifestRequest, opts ...grpc.CallOption) (*CreateManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateManifestResponse)
	err := c.cc.Invoke(ctx, ManifestAPI_CreateManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manifestAPIClient) ListManifests(ctx context.Context, in *ListManifestsRequest, opts ...grpc.CallOption) (*ListManifestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManifestsResponse)
	err := c.cc.Invoke(ctx, ManifestAPI_ListManifests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manifestAPIClient) GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManifestResponse)
	err := c.cc.Invoke(ctx, ManifestAPI_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manifestAPIClient) UpdateManifest(ctx context.Context, in *UpdateManifestRequest, opts ...grpc.CallOption) (*UpdateManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateManifestResponse)
	err := c.cc.Invoke(ctx, ManifestAPI_UpdateManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manifestAPIClient) DeleteManifest(ctx context.Context, in *DeleteManifestRequest, opts ...grpc.CallOption) (*DeleteManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteManifestResponse)
	err := c.cc.Invoke(ctx, ManifestAPI_DeleteManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManifestAPIServer is the server API for ManifestAPI service.
// All implementations should embed UnimplementedManifestAPIServer
// for forward compatibility.
type ManifestAPIServer interface {
	CreateManifest(context.Context, *CreateManifestRequest) (*CreateManifestResponse, error)
	ListManifests(context.Context, *ListManifestsRequest) (*ListManifestsResponse, error)
	GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error)
	UpdateManifest(context.Context, *UpdateManifestRequest) (*UpdateManifestResponse, error)
	DeleteManifest(context.Context, *DeleteManifestRequest) (*DeleteManifestResponse, error)
}

// UnimplementedManifestAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManifestAPIServer struct{}

func (UnimplementedManifestAPIServer) CreateManifest(context.Context, *CreateManifestRequest) (*CreateManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateManifest not implemented")
}
func (UnimplementedManifestAPIServer) ListManifests(context.Context, *ListManifestsRequest) (*ListManifestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListManifests not implemented")
}
func (UnimplementedManifestAPIServer) GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedManifestAPIServer) UpdateManifest(context.Context, *UpdateManifestRequest) (*UpdateManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateManifest not implemented")
}
func (UnimplementedManifestAPIServer) DeleteManifest(context.Context, *DeleteManifestRequest) (*DeleteManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteManifest not implemented")
}
func (UnimplementedManifestAPIServer) testEmbeddedByValue() {}

// UnsafeManifestAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManifestAPIServer will
// result in compilation errors.
type UnsafeManifestAPIServer interface {
	mustEmbedUnimplementedManifestAPIServer()
}

func RegisterManifestAPIServer(s grpc.ServiceRegistrar, srv ManifestAPIServer) {
	// If the following call pancis, it indicates UnimplementedManifestAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManifestAPI_ServiceDesc, srv)
}

func _ManifestAPI_CreateManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestAPIServer).CreateManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManifestAPI_CreateManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestAPIServer).CreateManifest(ctx, req.(*CreateManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManifestAPI_ListManifests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManifestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestAPIServer).ListManifests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManifestAPI_ListManifests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestAPIServer).ListManifests(ctx, req.(*ListManifestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManifestAPI_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestAPIServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManifestAPI_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestAPIServer).GetManifest(ctx, req.(*GetManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManifestAPI_UpdateManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestAPIServer).UpdateManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManifestAPI_UpdateManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestAPIServer).UpdateManifest(ctx, req.(*UpdateManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManifestAPI_DeleteManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestAPIServer).DeleteManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManifestAPI_DeleteManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestAPIServer).DeleteManifest(ctx, req.(*DeleteManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManifestAPI_ServiceDesc is the grpc.ServiceDesc for ManifestAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManifestAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admiral.manifest.v1.ManifestAPI",
	HandlerType: (*ManifestAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateManifest",
			Handler:    _ManifestAPI_CreateManifest_Handler,
		},
		{
			MethodName: "ListManifests",
			Handler:    _ManifestAPI_ListManifests_Handler,
		},
		{
			MethodName: "GetManifest",
			Handler:    _ManifestAPI_GetManifest_Handler,
		},
		{
			MethodName: "UpdateManifest",
			Handler:    _ManifestAPI_UpdateManifest_Handler,
		},
		{
			MethodName: "DeleteManifest",
			Handler:    _ManifestAPI_DeleteManifest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manifest/v1/manifest.proto",
}
