// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: manifest/v1/manifest.proto

package manifestv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Manifest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Manifest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Manifest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ManifestMultiError, or nil
// if none found.
func (m *Manifest) ValidateAll() error {
	return m.validate(true)
}

func (m *Manifest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ApplicationId

	// no validation rules for VersionGroupId

	// no validation rules for Name

	// no validation rules for Version

	// no validation rules for IsLatest

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ManifestValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ManifestValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ManifestValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ManifestValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ManifestValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ManifestValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if m.File != nil {

		if all {
			switch v := interface{}(m.GetFile()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ManifestValidationError{
						field:  "File",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ManifestValidationError{
						field:  "File",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetFile()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ManifestValidationError{
					field:  "File",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ManifestMultiError(errors)
	}

	return nil
}

// ManifestMultiError is an error wrapping multiple validation errors returned
// by Manifest.ValidateAll() if the designated constraints aren't met.
type ManifestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ManifestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ManifestMultiError) AllErrors() []error { return m }

// ManifestValidationError is the validation error returned by
// Manifest.Validate if the designated constraints aren't met.
type ManifestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ManifestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ManifestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ManifestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ManifestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ManifestValidationError) ErrorName() string { return "ManifestValidationError" }

// Error satisfies the builtin error interface
func (e ManifestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sManifest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ManifestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ManifestValidationError{}

// Validate checks the field values on ManifestFile with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ManifestFile) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ManifestFile with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ManifestFileMultiError, or
// nil if none found.
func (m *ManifestFile) ValidateAll() error {
	return m.validate(true)
}

func (m *ManifestFile) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FileContent

	// no validation rules for ChecksumType

	// no validation rules for Checksum

	if len(errors) > 0 {
		return ManifestFileMultiError(errors)
	}

	return nil
}

// ManifestFileMultiError is an error wrapping multiple validation errors
// returned by ManifestFile.ValidateAll() if the designated constraints aren't met.
type ManifestFileMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ManifestFileMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ManifestFileMultiError) AllErrors() []error { return m }

// ManifestFileValidationError is the validation error returned by
// ManifestFile.Validate if the designated constraints aren't met.
type ManifestFileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ManifestFileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ManifestFileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ManifestFileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ManifestFileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ManifestFileValidationError) ErrorName() string { return "ManifestFileValidationError" }

// Error satisfies the builtin error interface
func (e ManifestFileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sManifestFile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ManifestFileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ManifestFileValidationError{}

// Validate checks the field values on CreateManifestRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateManifestRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateManifestRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateManifestRequestMultiError, or nil if none found.
func (m *CreateManifestRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateManifestRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ApplicationId

	// no validation rules for Name

	// no validation rules for FileContent

	if m.Description != nil {
		// no validation rules for Description
	}

	if len(errors) > 0 {
		return CreateManifestRequestMultiError(errors)
	}

	return nil
}

// CreateManifestRequestMultiError is an error wrapping multiple validation
// errors returned by CreateManifestRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateManifestRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateManifestRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateManifestRequestMultiError) AllErrors() []error { return m }

// CreateManifestRequestValidationError is the validation error returned by
// CreateManifestRequest.Validate if the designated constraints aren't met.
type CreateManifestRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateManifestRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateManifestRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateManifestRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateManifestRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateManifestRequestValidationError) ErrorName() string {
	return "CreateManifestRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateManifestRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateManifestRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateManifestRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateManifestRequestValidationError{}

// Validate checks the field values on CreateManifestResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateManifestResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateManifestResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateManifestResponseMultiError, or nil if none found.
func (m *CreateManifestResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateManifestResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetManifest()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateManifestResponseValidationError{
					field:  "Manifest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateManifestResponseValidationError{
					field:  "Manifest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetManifest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateManifestResponseValidationError{
				field:  "Manifest",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateManifestResponseMultiError(errors)
	}

	return nil
}

// CreateManifestResponseMultiError is an error wrapping multiple validation
// errors returned by CreateManifestResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateManifestResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateManifestResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateManifestResponseMultiError) AllErrors() []error { return m }

// CreateManifestResponseValidationError is the validation error returned by
// CreateManifestResponse.Validate if the designated constraints aren't met.
type CreateManifestResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateManifestResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateManifestResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateManifestResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateManifestResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateManifestResponseValidationError) ErrorName() string {
	return "CreateManifestResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateManifestResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateManifestResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateManifestResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateManifestResponseValidationError{}

// Validate checks the field values on ListManifestsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListManifestsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListManifestsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListManifestsRequestMultiError, or nil if none found.
func (m *ListManifestsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListManifestsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Filter

	// no validation rules for PageSize

	if m.PageToken != nil {
		// no validation rules for PageToken
	}

	if len(errors) > 0 {
		return ListManifestsRequestMultiError(errors)
	}

	return nil
}

// ListManifestsRequestMultiError is an error wrapping multiple validation
// errors returned by ListManifestsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListManifestsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListManifestsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListManifestsRequestMultiError) AllErrors() []error { return m }

// ListManifestsRequestValidationError is the validation error returned by
// ListManifestsRequest.Validate if the designated constraints aren't met.
type ListManifestsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListManifestsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListManifestsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListManifestsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListManifestsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListManifestsRequestValidationError) ErrorName() string {
	return "ListManifestsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListManifestsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListManifestsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListManifestsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListManifestsRequestValidationError{}

// Validate checks the field values on ListManifestsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListManifestsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListManifestsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListManifestsResponseMultiError, or nil if none found.
func (m *ListManifestsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListManifestsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetManifests() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListManifestsResponseValidationError{
						field:  fmt.Sprintf("Manifests[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListManifestsResponseValidationError{
						field:  fmt.Sprintf("Manifests[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListManifestsResponseValidationError{
					field:  fmt.Sprintf("Manifests[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListManifestsResponseMultiError(errors)
	}

	return nil
}

// ListManifestsResponseMultiError is an error wrapping multiple validation
// errors returned by ListManifestsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListManifestsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListManifestsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListManifestsResponseMultiError) AllErrors() []error { return m }

// ListManifestsResponseValidationError is the validation error returned by
// ListManifestsResponse.Validate if the designated constraints aren't met.
type ListManifestsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListManifestsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListManifestsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListManifestsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListManifestsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListManifestsResponseValidationError) ErrorName() string {
	return "ListManifestsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListManifestsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListManifestsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListManifestsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListManifestsResponseValidationError{}

// Validate checks the field values on GetManifestRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetManifestRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetManifestRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetManifestRequestMultiError, or nil if none found.
func (m *GetManifestRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetManifestRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetManifestRequestMultiError(errors)
	}

	return nil
}

// GetManifestRequestMultiError is an error wrapping multiple validation errors
// returned by GetManifestRequest.ValidateAll() if the designated constraints
// aren't met.
type GetManifestRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetManifestRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetManifestRequestMultiError) AllErrors() []error { return m }

// GetManifestRequestValidationError is the validation error returned by
// GetManifestRequest.Validate if the designated constraints aren't met.
type GetManifestRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetManifestRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetManifestRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetManifestRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetManifestRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetManifestRequestValidationError) ErrorName() string {
	return "GetManifestRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetManifestRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetManifestRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetManifestRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetManifestRequestValidationError{}

// Validate checks the field values on GetManifestResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetManifestResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetManifestResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetManifestResponseMultiError, or nil if none found.
func (m *GetManifestResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetManifestResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetManifest()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetManifestResponseValidationError{
					field:  "Manifest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetManifestResponseValidationError{
					field:  "Manifest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetManifest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetManifestResponseValidationError{
				field:  "Manifest",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetManifestResponseMultiError(errors)
	}

	return nil
}

// GetManifestResponseMultiError is an error wrapping multiple validation
// errors returned by GetManifestResponse.ValidateAll() if the designated
// constraints aren't met.
type GetManifestResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetManifestResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetManifestResponseMultiError) AllErrors() []error { return m }

// GetManifestResponseValidationError is the validation error returned by
// GetManifestResponse.Validate if the designated constraints aren't met.
type GetManifestResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetManifestResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetManifestResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetManifestResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetManifestResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetManifestResponseValidationError) ErrorName() string {
	return "GetManifestResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetManifestResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetManifestResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetManifestResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetManifestResponseValidationError{}

// Validate checks the field values on UpdateManifestRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateManifestRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateManifestRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateManifestRequestMultiError, or nil if none found.
func (m *UpdateManifestRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateManifestRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ApplicationId

	// no validation rules for VersionGroupId

	if m.Name != nil {
		// no validation rules for Name
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if m.FileContent != nil {
		// no validation rules for FileContent
	}

	if len(errors) > 0 {
		return UpdateManifestRequestMultiError(errors)
	}

	return nil
}

// UpdateManifestRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateManifestRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateManifestRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateManifestRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateManifestRequestMultiError) AllErrors() []error { return m }

// UpdateManifestRequestValidationError is the validation error returned by
// UpdateManifestRequest.Validate if the designated constraints aren't met.
type UpdateManifestRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateManifestRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateManifestRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateManifestRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateManifestRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateManifestRequestValidationError) ErrorName() string {
	return "UpdateManifestRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateManifestRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateManifestRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateManifestRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateManifestRequestValidationError{}

// Validate checks the field values on UpdateManifestResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateManifestResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateManifestResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateManifestResponseMultiError, or nil if none found.
func (m *UpdateManifestResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateManifestResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetManifest()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateManifestResponseValidationError{
					field:  "Manifest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateManifestResponseValidationError{
					field:  "Manifest",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetManifest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateManifestResponseValidationError{
				field:  "Manifest",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateManifestResponseMultiError(errors)
	}

	return nil
}

// UpdateManifestResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateManifestResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateManifestResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateManifestResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateManifestResponseMultiError) AllErrors() []error { return m }

// UpdateManifestResponseValidationError is the validation error returned by
// UpdateManifestResponse.Validate if the designated constraints aren't met.
type UpdateManifestResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateManifestResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateManifestResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateManifestResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateManifestResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateManifestResponseValidationError) ErrorName() string {
	return "UpdateManifestResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateManifestResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateManifestResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateManifestResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateManifestResponseValidationError{}

// Validate checks the field values on DeleteManifestRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteManifestRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteManifestRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteManifestRequestMultiError, or nil if none found.
func (m *DeleteManifestRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteManifestRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for VersionGroupId

	if len(errors) > 0 {
		return DeleteManifestRequestMultiError(errors)
	}

	return nil
}

// DeleteManifestRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteManifestRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteManifestRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteManifestRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteManifestRequestMultiError) AllErrors() []error { return m }

// DeleteManifestRequestValidationError is the validation error returned by
// DeleteManifestRequest.Validate if the designated constraints aren't met.
type DeleteManifestRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteManifestRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteManifestRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteManifestRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteManifestRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteManifestRequestValidationError) ErrorName() string {
	return "DeleteManifestRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteManifestRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteManifestRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteManifestRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteManifestRequestValidationError{}

// Validate checks the field values on DeleteManifestResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteManifestResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteManifestResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteManifestResponseMultiError, or nil if none found.
func (m *DeleteManifestResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteManifestResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteManifestResponseMultiError(errors)
	}

	return nil
}

// DeleteManifestResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteManifestResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteManifestResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteManifestResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteManifestResponseMultiError) AllErrors() []error { return m }

// DeleteManifestResponseValidationError is the validation error returned by
// DeleteManifestResponse.Validate if the designated constraints aren't met.
type DeleteManifestResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteManifestResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteManifestResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteManifestResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteManifestResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteManifestResponseValidationError) ErrorName() string {
	return "DeleteManifestResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteManifestResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteManifestResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteManifestResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteManifestResponseValidationError{}
