// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: manifest/v1/manifest.proto

package manifestv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manifest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId  string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	VersionGroupId string                 `protobuf:"bytes,3,opt,name=version_group_id,json=versionGroupId,proto3" json:"version_group_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	File           *ManifestFile          `protobuf:"bytes,6,opt,name=file,proto3,oneof" json:"file,omitempty"`
	Version        uint32                 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	IsLatest       bool                   `protobuf:"varint,8,opt,name=is_latest,json=isLatest,proto3" json:"is_latest,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manifest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Manifest) GetVersionGroupId() string {
	if x != nil {
		return x.VersionGroupId
	}
	return ""
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Manifest) GetFile() *ManifestFile {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *Manifest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Manifest) GetIsLatest() bool {
	if x != nil {
		return x.IsLatest
	}
	return false
}

func (x *Manifest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Manifest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ManifestFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	ChecksumType  string                 `protobuf:"bytes,2,opt,name=checksum_type,json=checksumType,proto3" json:"checksum_type,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestFile) Reset() {
	*x = ManifestFile{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestFile) ProtoMessage() {}

func (x *ManifestFile) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestFile.ProtoReflect.Descriptor instead.
func (*ManifestFile) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestFile) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *ManifestFile) GetChecksumType() string {
	if x != nil {
		return x.ChecksumType
	}
	return ""
}

func (x *ManifestFile) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type CreateManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,4,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManifestRequest) Reset() {
	*x = CreateManifestRequest{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManifestRequest) ProtoMessage() {}

func (x *CreateManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManifestRequest.ProtoReflect.Descriptor instead.
func (*CreateManifestRequest) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *CreateManifestRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CreateManifestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateManifestRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateManifestRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type CreateManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManifestResponse) Reset() {
	*x = CreateManifestResponse{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManifestResponse) ProtoMessage() {}

func (x *CreateManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManifestResponse.ProtoReflect.Descriptor instead.
func (*CreateManifestResponse) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *CreateManifestResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type ListManifestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManifestsRequest) Reset() {
	*x = ListManifestsRequest{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManifestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManifestsRequest) ProtoMessage() {}

func (x *ListManifestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManifestsRequest.ProtoReflect.Descriptor instead.
func (*ListManifestsRequest) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{4}
}

func (x *ListManifestsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListManifestsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListManifestsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListManifestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifests     []*Manifest            `protobuf:"bytes,1,rep,name=manifests,proto3" json:"manifests,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManifestsResponse) Reset() {
	*x = ListManifestsResponse{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManifestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManifestsResponse) ProtoMessage() {}

func (x *ListManifestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManifestsResponse.ProtoReflect.Descriptor instead.
func (*ListManifestsResponse) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{5}
}

func (x *ListManifestsResponse) GetManifests() []*Manifest {
	if x != nil {
		return x.Manifests
	}
	return nil
}

func (x *ListManifestsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{6}
}

func (x *GetManifestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{7}
}

func (x *GetManifestResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type UpdateManifestRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId  string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	VersionGroupId string                 `protobuf:"bytes,1,opt,name=version_group_id,json=versionGroupId,proto3" json:"version_group_id,omitempty"`
	Name           *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	FileContent    []byte                 `protobuf:"bytes,5,opt,name=file_content,json=fileContent,proto3,oneof" json:"file_content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateManifestRequest) Reset() {
	*x = UpdateManifestRequest{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManifestRequest) ProtoMessage() {}

func (x *UpdateManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManifestRequest.ProtoReflect.Descriptor instead.
func (*UpdateManifestRequest) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateManifestRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *UpdateManifestRequest) GetVersionGroupId() string {
	if x != nil {
		return x.VersionGroupId
	}
	return ""
}

func (x *UpdateManifestRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateManifestRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateManifestRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type UpdateManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManifestResponse) Reset() {
	*x = UpdateManifestResponse{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManifestResponse) ProtoMessage() {}

func (x *UpdateManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManifestResponse.ProtoReflect.Descriptor instead.
func (*UpdateManifestResponse) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateManifestResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type DeleteManifestRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VersionGroupId string                 `protobuf:"bytes,1,opt,name=version_group_id,json=versionGroupId,proto3" json:"version_group_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteManifestRequest) Reset() {
	*x = DeleteManifestRequest{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManifestRequest) ProtoMessage() {}

func (x *DeleteManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManifestRequest.ProtoReflect.Descriptor instead.
func (*DeleteManifestRequest) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteManifestRequest) GetVersionGroupId() string {
	if x != nil {
		return x.VersionGroupId
	}
	return ""
}

type DeleteManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManifestResponse) Reset() {
	*x = DeleteManifestResponse{}
	mi := &file_manifest_v1_manifest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManifestResponse) ProtoMessage() {}

func (x *DeleteManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_v1_manifest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManifestResponse.ProtoReflect.Descriptor instead.
func (*DeleteManifestResponse) Descriptor() ([]byte, []int) {
	return file_manifest_v1_manifest_proto_rawDescGZIP(), []int{11}
}

var File_manifest_v1_manifest_proto protoreflect.FileDescriptor

const file_manifest_v1_manifest_proto_rawDesc = "" +
	"\n" +
	"\x1amanifest/v1/manifest.proto\x12\x13admiral.manifest.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xdc\x03\n" +
	"\bManifest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12/\n" +
	"\x0eapplication_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x122\n" +
	"\x10version_group_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eversionGroupId\x12\x1e\n" +
	"\x04name\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12/\n" +
	"\vdescription\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bH\x00R\vdescription\x88\x01\x01\x12:\n" +
	"\x04file\x18\x06 \x01(\v2!.admiral.manifest.v1.ManifestFileH\x01R\x04file\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\a \x01(\rR\aversion\x12\x1b\n" +
	"\tis_latest\x18\b \x01(\bR\bisLatest\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_file\"\xae\x01\n" +
	"\fManifestFile\x12/\n" +
	"\ffile_content\x18\x01 \x01(\fB\f\xbaH\tz\a\x10\x01\x18\x80\x80\x80\x05R\vfileContent\x126\n" +
	"\rchecksum_type\x18\x02 \x01(\tB\x11\xbaH\x0er\f\x10\x01\x182R\x06sha256R\fchecksumType\x125\n" +
	"\bchecksum\x18\x03 \x01(\tB\x19\xbaH\x16r\x14\x10 \x18@2\x0e^[0-9a-fA-F]+$R\bchecksum\"\xda\x01\n" +
	"\x15CreateManifestRequest\x12/\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12/\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bH\x00R\vdescription\x88\x01\x01\x12/\n" +
	"\ffile_content\x18\x04 \x01(\fB\f\xbaH\tz\a\x10\x01\x18\x80\x80\x80\x05R\vfileContentB\x0e\n" +
	"\f_description\"S\n" +
	"\x16CreateManifestResponse\x129\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1d.admiral.manifest.v1.ManifestR\bmanifest\"~\n" +
	"\x14ListManifestsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x00R\tpageToken\x88\x01\x01B\r\n" +
	"\v_page_token\"|\n" +
	"\x15ListManifestsResponse\x12;\n" +
	"\tmanifests\x18\x01 \x03(\v2\x1d.admiral.manifest.v1.ManifestR\tmanifests\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\".\n" +
	"\x12GetManifestRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"P\n" +
	"\x13GetManifestResponse\x129\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1d.admiral.manifest.v1.ManifestR\bmanifest\"\xae\x02\n" +
	"\x15UpdateManifestRequest\x12/\n" +
	"\x0eapplication_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x122\n" +
	"\x10version_group_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eversionGroupId\x12!\n" +
	"\x04name\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01H\x00R\x04name\x88\x01\x01\x12/\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bH\x01R\vdescription\x88\x01\x01\x122\n" +
	"\ffile_content\x18\x05 \x01(\fB\n" +
	"\xbaH\az\x05\x18\x80\x80\x80\x05H\x02R\vfileContent\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_file_content\"S\n" +
	"\x16UpdateManifestResponse\x129\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1d.admiral.manifest.v1.ManifestR\bmanifest\"K\n" +
	"\x15DeleteManifestRequest\x122\n" +
	"\x10version_group_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0eversionGroupId\"\x18\n" +
	"\x16DeleteManifestResponse2\xd5\x05\n" +
	"\vManifestAPI\x12\x87\x01\n" +
	"\x0eCreateManifest\x12*.admiral.manifest.v1.CreateManifestRequest\x1a+.admiral.manifest.v1.CreateManifestResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/manifests\x12\x81\x01\n" +
	"\rListManifests\x12).admiral.manifest.v1.ListManifestsRequest\x1a*.admiral.manifest.v1.ListManifestsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/manifests\x12\x80\x01\n" +
	"\vGetManifest\x12'.admiral.manifest.v1.GetManifestRequest\x1a(.admiral.manifest.v1.GetManifestResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/manifests/{id}\x12\x9a\x01\n" +
	"\x0eUpdateManifest\x12*.admiral.manifest.v1.UpdateManifestRequest\x1a+.admiral.manifest.v1.UpdateManifestResponse\"/\x82\xd3\xe4\x93\x02):\x01*\x1a$/api/v1/manifests/{version_group_id}\x12\x97\x01\n" +
	"\x0eDeleteManifest\x12*.admiral.manifest.v1.DeleteManifestRequest\x1a+.admiral.manifest.v1.DeleteManifestResponse\",\x82\xd3\xe4\x93\x02&*$/api/v1/manifests/{version_group_id}B\xc8\x01\n" +
	"\x17com.admiral.manifest.v1B\rManifestProtoP\x01Z0go.admiral.io/admiral/api/manifest/v1;manifestv1\xa2\x02\x03AMX\xaa\x02\x13Admiral.Manifest.V1\xca\x02\x13Admiral\\Manifest\\V1\xe2\x02\x1fAdmiral\\Manifest\\V1\\GPBMetadata\xea\x02\x15Admiral::Manifest::V1b\x06proto3"

var (
	file_manifest_v1_manifest_proto_rawDescOnce sync.Once
	file_manifest_v1_manifest_proto_rawDescData []byte
)

func file_manifest_v1_manifest_proto_rawDescGZIP() []byte {
	file_manifest_v1_manifest_proto_rawDescOnce.Do(func() {
		file_manifest_v1_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manifest_v1_manifest_proto_rawDesc), len(file_manifest_v1_manifest_proto_rawDesc)))
	})
	return file_manifest_v1_manifest_proto_rawDescData
}

var file_manifest_v1_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_manifest_v1_manifest_proto_goTypes = []any{
	(*Manifest)(nil),               // 0: admiral.manifest.v1.Manifest
	(*ManifestFile)(nil),           // 1: admiral.manifest.v1.ManifestFile
	(*CreateManifestRequest)(nil),  // 2: admiral.manifest.v1.CreateManifestRequest
	(*CreateManifestResponse)(nil), // 3: admiral.manifest.v1.CreateManifestResponse
	(*ListManifestsRequest)(nil),   // 4: admiral.manifest.v1.ListManifestsRequest
	(*ListManifestsResponse)(nil),  // 5: admiral.manifest.v1.ListManifestsResponse
	(*GetManifestRequest)(nil),     // 6: admiral.manifest.v1.GetManifestRequest
	(*GetManifestResponse)(nil),    // 7: admiral.manifest.v1.GetManifestResponse
	(*UpdateManifestRequest)(nil),  // 8: admiral.manifest.v1.UpdateManifestRequest
	(*UpdateManifestResponse)(nil), // 9: admiral.manifest.v1.UpdateManifestResponse
	(*DeleteManifestRequest)(nil),  // 10: admiral.manifest.v1.DeleteManifestRequest
	(*DeleteManifestResponse)(nil), // 11: admiral.manifest.v1.DeleteManifestResponse
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_manifest_v1_manifest_proto_depIdxs = []int32{
	1,  // 0: admiral.manifest.v1.Manifest.file:type_name -> admiral.manifest.v1.ManifestFile
	12, // 1: admiral.manifest.v1.Manifest.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: admiral.manifest.v1.Manifest.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: admiral.manifest.v1.CreateManifestResponse.manifest:type_name -> admiral.manifest.v1.Manifest
	0,  // 4: admiral.manifest.v1.ListManifestsResponse.manifests:type_name -> admiral.manifest.v1.Manifest
	0,  // 5: admiral.manifest.v1.GetManifestResponse.manifest:type_name -> admiral.manifest.v1.Manifest
	0,  // 6: admiral.manifest.v1.UpdateManifestResponse.manifest:type_name -> admiral.manifest.v1.Manifest
	2,  // 7: admiral.manifest.v1.ManifestAPI.CreateManifest:input_type -> admiral.manifest.v1.CreateManifestRequest
	4,  // 8: admiral.manifest.v1.ManifestAPI.ListManifests:input_type -> admiral.manifest.v1.ListManifestsRequest
	6,  // 9: admiral.manifest.v1.ManifestAPI.GetManifest:input_type -> admiral.manifest.v1.GetManifestRequest
	8,  // 10: admiral.manifest.v1.ManifestAPI.UpdateManifest:input_type -> admiral.manifest.v1.UpdateManifestRequest
	10, // 11: admiral.manifest.v1.ManifestAPI.DeleteManifest:input_type -> admiral.manifest.v1.DeleteManifestRequest
	3,  // 12: admiral.manifest.v1.ManifestAPI.CreateManifest:output_type -> admiral.manifest.v1.CreateManifestResponse
	5,  // 13: admiral.manifest.v1.ManifestAPI.ListManifests:output_type -> admiral.manifest.v1.ListManifestsResponse
	7,  // 14: admiral.manifest.v1.ManifestAPI.GetManifest:output_type -> admiral.manifest.v1.GetManifestResponse
	9,  // 15: admiral.manifest.v1.ManifestAPI.UpdateManifest:output_type -> admiral.manifest.v1.UpdateManifestResponse
	11, // 16: admiral.manifest.v1.ManifestAPI.DeleteManifest:output_type -> admiral.manifest.v1.DeleteManifestResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_manifest_v1_manifest_proto_init() }
func file_manifest_v1_manifest_proto_init() {
	if File_manifest_v1_manifest_proto != nil {
		return
	}
	file_manifest_v1_manifest_proto_msgTypes[0].OneofWrappers = []any{}
	file_manifest_v1_manifest_proto_msgTypes[2].OneofWrappers = []any{}
	file_manifest_v1_manifest_proto_msgTypes[4].OneofWrappers = []any{}
	file_manifest_v1_manifest_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manifest_v1_manifest_proto_rawDesc), len(file_manifest_v1_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manifest_v1_manifest_proto_goTypes,
		DependencyIndexes: file_manifest_v1_manifest_proto_depIdxs,
		MessageInfos:      file_manifest_v1_manifest_proto_msgTypes,
	}.Build()
	File_manifest_v1_manifest_proto = out.File
	file_manifest_v1_manifest_proto_goTypes = nil
	file_manifest_v1_manifest_proto_depIdxs = nil
}
