// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: environment/v1/environment.proto

package environmentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/admiral/api/environment/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EnvironmentAPIName is the fully-qualified name of the EnvironmentAPI service.
	EnvironmentAPIName = "admiral.environment.v1.EnvironmentAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EnvironmentAPICreateEnvironmentProcedure is the fully-qualified name of the EnvironmentAPI's
	// CreateEnvironment RPC.
	EnvironmentAPICreateEnvironmentProcedure = "/admiral.environment.v1.EnvironmentAPI/CreateEnvironment"
	// EnvironmentAPIListEnvironmentsProcedure is the fully-qualified name of the EnvironmentAPI's
	// ListEnvironments RPC.
	EnvironmentAPIListEnvironmentsProcedure = "/admiral.environment.v1.EnvironmentAPI/ListEnvironments"
	// EnvironmentAPIGetEnvironmentProcedure is the fully-qualified name of the EnvironmentAPI's
	// GetEnvironment RPC.
	EnvironmentAPIGetEnvironmentProcedure = "/admiral.environment.v1.EnvironmentAPI/GetEnvironment"
	// EnvironmentAPIUpdateEnvironmentProcedure is the fully-qualified name of the EnvironmentAPI's
	// UpdateEnvironment RPC.
	EnvironmentAPIUpdateEnvironmentProcedure = "/admiral.environment.v1.EnvironmentAPI/UpdateEnvironment"
	// EnvironmentAPIDeleteEnvironmentProcedure is the fully-qualified name of the EnvironmentAPI's
	// DeleteEnvironment RPC.
	EnvironmentAPIDeleteEnvironmentProcedure = "/admiral.environment.v1.EnvironmentAPI/DeleteEnvironment"
)

// EnvironmentAPIClient is a client for the admiral.environment.v1.EnvironmentAPI service.
type EnvironmentAPIClient interface {
	CreateEnvironment(context.Context, *connect.Request[v1.CreateEnvironmentRequest]) (*connect.Response[v1.CreateEnvironmentResponse], error)
	ListEnvironments(context.Context, *connect.Request[v1.ListEnvironmentsRequest]) (*connect.Response[v1.ListEnvironmentsResponse], error)
	GetEnvironment(context.Context, *connect.Request[v1.GetEnvironmentRequest]) (*connect.Response[v1.GetEnvironmentResponse], error)
	UpdateEnvironment(context.Context, *connect.Request[v1.UpdateEnvironmentRequest]) (*connect.Response[v1.UpdateEnvironmentResponse], error)
	DeleteEnvironment(context.Context, *connect.Request[v1.DeleteEnvironmentRequest]) (*connect.Response[v1.DeleteEnvironmentResponse], error)
}

// NewEnvironmentAPIClient constructs a client for the admiral.environment.v1.EnvironmentAPI
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEnvironmentAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EnvironmentAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	environmentAPIMethods := v1.File_environment_v1_environment_proto.Services().ByName("EnvironmentAPI").Methods()
	return &environmentAPIClient{
		createEnvironment: connect.NewClient[v1.CreateEnvironmentRequest, v1.CreateEnvironmentResponse](
			httpClient,
			baseURL+EnvironmentAPICreateEnvironmentProcedure,
			connect.WithSchema(environmentAPIMethods.ByName("CreateEnvironment")),
			connect.WithClientOptions(opts...),
		),
		listEnvironments: connect.NewClient[v1.ListEnvironmentsRequest, v1.ListEnvironmentsResponse](
			httpClient,
			baseURL+EnvironmentAPIListEnvironmentsProcedure,
			connect.WithSchema(environmentAPIMethods.ByName("ListEnvironments")),
			connect.WithClientOptions(opts...),
		),
		getEnvironment: connect.NewClient[v1.GetEnvironmentRequest, v1.GetEnvironmentResponse](
			httpClient,
			baseURL+EnvironmentAPIGetEnvironmentProcedure,
			connect.WithSchema(environmentAPIMethods.ByName("GetEnvironment")),
			connect.WithClientOptions(opts...),
		),
		updateEnvironment: connect.NewClient[v1.UpdateEnvironmentRequest, v1.UpdateEnvironmentResponse](
			httpClient,
			baseURL+EnvironmentAPIUpdateEnvironmentProcedure,
			connect.WithSchema(environmentAPIMethods.ByName("UpdateEnvironment")),
			connect.WithClientOptions(opts...),
		),
		deleteEnvironment: connect.NewClient[v1.DeleteEnvironmentRequest, v1.DeleteEnvironmentResponse](
			httpClient,
			baseURL+EnvironmentAPIDeleteEnvironmentProcedure,
			connect.WithSchema(environmentAPIMethods.ByName("DeleteEnvironment")),
			connect.WithClientOptions(opts...),
		),
	}
}

// environmentAPIClient implements EnvironmentAPIClient.
type environmentAPIClient struct {
	createEnvironment *connect.Client[v1.CreateEnvironmentRequest, v1.CreateEnvironmentResponse]
	listEnvironments  *connect.Client[v1.ListEnvironmentsRequest, v1.ListEnvironmentsResponse]
	getEnvironment    *connect.Client[v1.GetEnvironmentRequest, v1.GetEnvironmentResponse]
	updateEnvironment *connect.Client[v1.UpdateEnvironmentRequest, v1.UpdateEnvironmentResponse]
	deleteEnvironment *connect.Client[v1.DeleteEnvironmentRequest, v1.DeleteEnvironmentResponse]
}

// CreateEnvironment calls admiral.environment.v1.EnvironmentAPI.CreateEnvironment.
func (c *environmentAPIClient) CreateEnvironment(ctx context.Context, req *connect.Request[v1.CreateEnvironmentRequest]) (*connect.Response[v1.CreateEnvironmentResponse], error) {
	return c.createEnvironment.CallUnary(ctx, req)
}

// ListEnvironments calls admiral.environment.v1.EnvironmentAPI.ListEnvironments.
func (c *environmentAPIClient) ListEnvironments(ctx context.Context, req *connect.Request[v1.ListEnvironmentsRequest]) (*connect.Response[v1.ListEnvironmentsResponse], error) {
	return c.listEnvironments.CallUnary(ctx, req)
}

// GetEnvironment calls admiral.environment.v1.EnvironmentAPI.GetEnvironment.
func (c *environmentAPIClient) GetEnvironment(ctx context.Context, req *connect.Request[v1.GetEnvironmentRequest]) (*connect.Response[v1.GetEnvironmentResponse], error) {
	return c.getEnvironment.CallUnary(ctx, req)
}

// UpdateEnvironment calls admiral.environment.v1.EnvironmentAPI.UpdateEnvironment.
func (c *environmentAPIClient) UpdateEnvironment(ctx context.Context, req *connect.Request[v1.UpdateEnvironmentRequest]) (*connect.Response[v1.UpdateEnvironmentResponse], error) {
	return c.updateEnvironment.CallUnary(ctx, req)
}

// DeleteEnvironment calls admiral.environment.v1.EnvironmentAPI.DeleteEnvironment.
func (c *environmentAPIClient) DeleteEnvironment(ctx context.Context, req *connect.Request[v1.DeleteEnvironmentRequest]) (*connect.Response[v1.DeleteEnvironmentResponse], error) {
	return c.deleteEnvironment.CallUnary(ctx, req)
}

// EnvironmentAPIHandler is an implementation of the admiral.environment.v1.EnvironmentAPI service.
type EnvironmentAPIHandler interface {
	CreateEnvironment(context.Context, *connect.Request[v1.CreateEnvironmentRequest]) (*connect.Response[v1.CreateEnvironmentResponse], error)
	ListEnvironments(context.Context, *connect.Request[v1.ListEnvironmentsRequest]) (*connect.Response[v1.ListEnvironmentsResponse], error)
	GetEnvironment(context.Context, *connect.Request[v1.GetEnvironmentRequest]) (*connect.Response[v1.GetEnvironmentResponse], error)
	UpdateEnvironment(context.Context, *connect.Request[v1.UpdateEnvironmentRequest]) (*connect.Response[v1.UpdateEnvironmentResponse], error)
	DeleteEnvironment(context.Context, *connect.Request[v1.DeleteEnvironmentRequest]) (*connect.Response[v1.DeleteEnvironmentResponse], error)
}

// NewEnvironmentAPIHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEnvironmentAPIHandler(svc EnvironmentAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	environmentAPIMethods := v1.File_environment_v1_environment_proto.Services().ByName("EnvironmentAPI").Methods()
	environmentAPICreateEnvironmentHandler := connect.NewUnaryHandler(
		EnvironmentAPICreateEnvironmentProcedure,
		svc.CreateEnvironment,
		connect.WithSchema(environmentAPIMethods.ByName("CreateEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	environmentAPIListEnvironmentsHandler := connect.NewUnaryHandler(
		EnvironmentAPIListEnvironmentsProcedure,
		svc.ListEnvironments,
		connect.WithSchema(environmentAPIMethods.ByName("ListEnvironments")),
		connect.WithHandlerOptions(opts...),
	)
	environmentAPIGetEnvironmentHandler := connect.NewUnaryHandler(
		EnvironmentAPIGetEnvironmentProcedure,
		svc.GetEnvironment,
		connect.WithSchema(environmentAPIMethods.ByName("GetEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	environmentAPIUpdateEnvironmentHandler := connect.NewUnaryHandler(
		EnvironmentAPIUpdateEnvironmentProcedure,
		svc.UpdateEnvironment,
		connect.WithSchema(environmentAPIMethods.ByName("UpdateEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	environmentAPIDeleteEnvironmentHandler := connect.NewUnaryHandler(
		EnvironmentAPIDeleteEnvironmentProcedure,
		svc.DeleteEnvironment,
		connect.WithSchema(environmentAPIMethods.ByName("DeleteEnvironment")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.environment.v1.EnvironmentAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EnvironmentAPICreateEnvironmentProcedure:
			environmentAPICreateEnvironmentHandler.ServeHTTP(w, r)
		case EnvironmentAPIListEnvironmentsProcedure:
			environmentAPIListEnvironmentsHandler.ServeHTTP(w, r)
		case EnvironmentAPIGetEnvironmentProcedure:
			environmentAPIGetEnvironmentHandler.ServeHTTP(w, r)
		case EnvironmentAPIUpdateEnvironmentProcedure:
			environmentAPIUpdateEnvironmentHandler.ServeHTTP(w, r)
		case EnvironmentAPIDeleteEnvironmentProcedure:
			environmentAPIDeleteEnvironmentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEnvironmentAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedEnvironmentAPIHandler struct{}

func (UnimplementedEnvironmentAPIHandler) CreateEnvironment(context.Context, *connect.Request[v1.CreateEnvironmentRequest]) (*connect.Response[v1.CreateEnvironmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.environment.v1.EnvironmentAPI.CreateEnvironment is not implemented"))
}

func (UnimplementedEnvironmentAPIHandler) ListEnvironments(context.Context, *connect.Request[v1.ListEnvironmentsRequest]) (*connect.Response[v1.ListEnvironmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.environment.v1.EnvironmentAPI.ListEnvironments is not implemented"))
}

func (UnimplementedEnvironmentAPIHandler) GetEnvironment(context.Context, *connect.Request[v1.GetEnvironmentRequest]) (*connect.Response[v1.GetEnvironmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.environment.v1.EnvironmentAPI.GetEnvironment is not implemented"))
}

func (UnimplementedEnvironmentAPIHandler) UpdateEnvironment(context.Context, *connect.Request[v1.UpdateEnvironmentRequest]) (*connect.Response[v1.UpdateEnvironmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.environment.v1.EnvironmentAPI.UpdateEnvironment is not implemented"))
}

func (UnimplementedEnvironmentAPIHandler) DeleteEnvironment(context.Context, *connect.Request[v1.DeleteEnvironmentRequest]) (*connect.Response[v1.DeleteEnvironmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.environment.v1.EnvironmentAPI.DeleteEnvironment is not implemented"))
}
