// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: revision/v1/revision.proto

package revisionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RevisionAPI_CreateRevision_FullMethodName = "/admiral.revision.v1.RevisionAPI/CreateRevision"
)

// RevisionAPIClient is the client API for RevisionAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RevisionAPIClient interface {
	CreateRevision(ctx context.Context, in *CreateRevisionRequest, opts ...grpc.CallOption) (*CreateRevisionResponse, error)
}

type revisionAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewRevisionAPIClient(cc grpc.ClientConnInterface) RevisionAPIClient {
	return &revisionAPIClient{cc}
}

func (c *revisionAPIClient) CreateRevision(ctx context.Context, in *CreateRevisionRequest, opts ...grpc.CallOption) (*CreateRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRevisionResponse)
	err := c.cc.Invoke(ctx, RevisionAPI_CreateRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RevisionAPIServer is the server API for RevisionAPI service.
// All implementations should embed UnimplementedRevisionAPIServer
// for forward compatibility.
type RevisionAPIServer interface {
	CreateRevision(context.Context, *CreateRevisionRequest) (*CreateRevisionResponse, error)
}

// UnimplementedRevisionAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRevisionAPIServer struct{}

func (UnimplementedRevisionAPIServer) CreateRevision(context.Context, *CreateRevisionRequest) (*CreateRevisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRevision not implemented")
}
func (UnimplementedRevisionAPIServer) testEmbeddedByValue() {}

// UnsafeRevisionAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RevisionAPIServer will
// result in compilation errors.
type UnsafeRevisionAPIServer interface {
	mustEmbedUnimplementedRevisionAPIServer()
}

func RegisterRevisionAPIServer(s grpc.ServiceRegistrar, srv RevisionAPIServer) {
	// If the following call pancis, it indicates UnimplementedRevisionAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RevisionAPI_ServiceDesc, srv)
}

func _RevisionAPI_CreateRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevisionAPIServer).CreateRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevisionAPI_CreateRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevisionAPIServer).CreateRevision(ctx, req.(*CreateRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RevisionAPI_ServiceDesc is the grpc.ServiceDesc for RevisionAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RevisionAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admiral.revision.v1.RevisionAPI",
	HandlerType: (*RevisionAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRevision",
			Handler:    _RevisionAPI_CreateRevision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "revision/v1/revision.proto",
}
