// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: revision/v1/revision.proto

package revisionv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Revision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,3,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_revision_v1_revision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_revision_v1_revision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_revision_v1_revision_proto_rawDescGZIP(), []int{0}
}

func (x *Revision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Revision) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Revision) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *Revision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Revision) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRevisionRequest) Reset() {
	*x = CreateRevisionRequest{}
	mi := &file_revision_v1_revision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRevisionRequest) ProtoMessage() {}

func (x *CreateRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_revision_v1_revision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRevisionRequest.ProtoReflect.Descriptor instead.
func (*CreateRevisionRequest) Descriptor() ([]byte, []int) {
	return file_revision_v1_revision_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRevisionRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CreateRevisionRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

type CreateRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *Revision              `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRevisionResponse) Reset() {
	*x = CreateRevisionResponse{}
	mi := &file_revision_v1_revision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRevisionResponse) ProtoMessage() {}

func (x *CreateRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_revision_v1_revision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRevisionResponse.ProtoReflect.Descriptor instead.
func (*CreateRevisionResponse) Descriptor() ([]byte, []int) {
	return file_revision_v1_revision_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRevisionResponse) GetRevision() *Revision {
	if x != nil {
		return x.Revision
	}
	return nil
}

var File_revision_v1_revision_proto protoreflect.FileDescriptor

const file_revision_v1_revision_proto_rawDesc = "" +
	"\n" +
	"\x1arevision/v1/revision.proto\x12\x13admiral.revision.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xfc\x01\n" +
	"\bRevision\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12/\n" +
	"\x0eapplication_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x12/\n" +
	"\x0eenvironment_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\renvironmentId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"y\n" +
	"\x15CreateRevisionRequest\x12/\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x12/\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\renvironmentId\"S\n" +
	"\x16CreateRevisionResponse\x129\n" +
	"\brevision\x18\x01 \x01(\v2\x1d.admiral.revision.v1.RevisionR\brevision2\x97\x01\n" +
	"\vRevisionAPI\x12\x87\x01\n" +
	"\x0eCreateRevision\x12*.admiral.revision.v1.CreateRevisionRequest\x1a+.admiral.revision.v1.CreateRevisionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/revisionsB\xc8\x01\n" +
	"\x17com.admiral.revision.v1B\rRevisionProtoP\x01Z0go.admiral.io/admiral/api/revision/v1;revisionv1\xa2\x02\x03ARX\xaa\x02\x13Admiral.Revision.V1\xca\x02\x13Admiral\\Revision\\V1\xe2\x02\x1fAdmiral\\Revision\\V1\\GPBMetadata\xea\x02\x15Admiral::Revision::V1b\x06proto3"

var (
	file_revision_v1_revision_proto_rawDescOnce sync.Once
	file_revision_v1_revision_proto_rawDescData []byte
)

func file_revision_v1_revision_proto_rawDescGZIP() []byte {
	file_revision_v1_revision_proto_rawDescOnce.Do(func() {
		file_revision_v1_revision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_revision_v1_revision_proto_rawDesc), len(file_revision_v1_revision_proto_rawDesc)))
	})
	return file_revision_v1_revision_proto_rawDescData
}

var file_revision_v1_revision_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_revision_v1_revision_proto_goTypes = []any{
	(*Revision)(nil),               // 0: admiral.revision.v1.Revision
	(*CreateRevisionRequest)(nil),  // 1: admiral.revision.v1.CreateRevisionRequest
	(*CreateRevisionResponse)(nil), // 2: admiral.revision.v1.CreateRevisionResponse
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_revision_v1_revision_proto_depIdxs = []int32{
	3, // 0: admiral.revision.v1.Revision.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: admiral.revision.v1.Revision.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: admiral.revision.v1.CreateRevisionResponse.revision:type_name -> admiral.revision.v1.Revision
	1, // 3: admiral.revision.v1.RevisionAPI.CreateRevision:input_type -> admiral.revision.v1.CreateRevisionRequest
	2, // 4: admiral.revision.v1.RevisionAPI.CreateRevision:output_type -> admiral.revision.v1.CreateRevisionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_revision_v1_revision_proto_init() }
func file_revision_v1_revision_proto_init() {
	if File_revision_v1_revision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_revision_v1_revision_proto_rawDesc), len(file_revision_v1_revision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_revision_v1_revision_proto_goTypes,
		DependencyIndexes: file_revision_v1_revision_proto_depIdxs,
		MessageInfos:      file_revision_v1_revision_proto_msgTypes,
	}.Build()
	File_revision_v1_revision_proto = out.File
	file_revision_v1_revision_proto_goTypes = nil
	file_revision_v1_revision_proto_depIdxs = nil
}
