// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: revision/v1/revision.proto

package revisionv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Revision with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Revision) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Revision with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RevisionMultiError, or nil
// if none found.
func (m *Revision) ValidateAll() error {
	return m.validate(true)
}

func (m *Revision) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ApplicationId

	// no validation rules for EnvironmentId

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RevisionValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RevisionValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RevisionValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RevisionMultiError(errors)
	}

	return nil
}

// RevisionMultiError is an error wrapping multiple validation errors returned
// by Revision.ValidateAll() if the designated constraints aren't met.
type RevisionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevisionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevisionMultiError) AllErrors() []error { return m }

// RevisionValidationError is the validation error returned by
// Revision.Validate if the designated constraints aren't met.
type RevisionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevisionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevisionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevisionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevisionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevisionValidationError) ErrorName() string { return "RevisionValidationError" }

// Error satisfies the builtin error interface
func (e RevisionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevision.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevisionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevisionValidationError{}

// Validate checks the field values on CreateRevisionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRevisionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRevisionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRevisionRequestMultiError, or nil if none found.
func (m *CreateRevisionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRevisionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ApplicationId

	// no validation rules for EnvironmentId

	if len(errors) > 0 {
		return CreateRevisionRequestMultiError(errors)
	}

	return nil
}

// CreateRevisionRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRevisionRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateRevisionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRevisionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRevisionRequestMultiError) AllErrors() []error { return m }

// CreateRevisionRequestValidationError is the validation error returned by
// CreateRevisionRequest.Validate if the designated constraints aren't met.
type CreateRevisionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRevisionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRevisionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRevisionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRevisionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRevisionRequestValidationError) ErrorName() string {
	return "CreateRevisionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRevisionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRevisionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRevisionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRevisionRequestValidationError{}

// Validate checks the field values on CreateRevisionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRevisionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRevisionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRevisionResponseMultiError, or nil if none found.
func (m *CreateRevisionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRevisionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRevision()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateRevisionResponseValidationError{
					field:  "Revision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateRevisionResponseValidationError{
					field:  "Revision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRevision()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateRevisionResponseValidationError{
				field:  "Revision",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateRevisionResponseMultiError(errors)
	}

	return nil
}

// CreateRevisionResponseMultiError is an error wrapping multiple validation
// errors returned by CreateRevisionResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateRevisionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRevisionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRevisionResponseMultiError) AllErrors() []error { return m }

// CreateRevisionResponseValidationError is the validation error returned by
// CreateRevisionResponse.Validate if the designated constraints aren't met.
type CreateRevisionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRevisionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRevisionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRevisionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRevisionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRevisionResponseValidationError) ErrorName() string {
	return "CreateRevisionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRevisionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRevisionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRevisionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRevisionResponseValidationError{}
