// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: manifest/v1/manifest.proto

package manifestv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/admiral/api/manifest/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ManifestAPIName is the fully-qualified name of the ManifestAPI service.
	ManifestAPIName = "admiral.manifest.v1.ManifestAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ManifestAPICreateManifestProcedure is the fully-qualified name of the ManifestAPI's
	// CreateManifest RPC.
	ManifestAPICreateManifestProcedure = "/admiral.manifest.v1.ManifestAPI/CreateManifest"
	// ManifestAPIListManifestsProcedure is the fully-qualified name of the ManifestAPI's ListManifests
	// RPC.
	ManifestAPIListManifestsProcedure = "/admiral.manifest.v1.ManifestAPI/ListManifests"
	// ManifestAPIGetManifestProcedure is the fully-qualified name of the ManifestAPI's GetManifest RPC.
	ManifestAPIGetManifestProcedure = "/admiral.manifest.v1.ManifestAPI/GetManifest"
	// ManifestAPIUpdateManifestProcedure is the fully-qualified name of the ManifestAPI's
	// UpdateManifest RPC.
	ManifestAPIUpdateManifestProcedure = "/admiral.manifest.v1.ManifestAPI/UpdateManifest"
	// ManifestAPIDeleteManifestProcedure is the fully-qualified name of the ManifestAPI's
	// DeleteManifest RPC.
	ManifestAPIDeleteManifestProcedure = "/admiral.manifest.v1.ManifestAPI/DeleteManifest"
)

// ManifestAPIClient is a client for the admiral.manifest.v1.ManifestAPI service.
type ManifestAPIClient interface {
	CreateManifest(context.Context, *connect.Request[v1.CreateManifestRequest]) (*connect.Response[v1.CreateManifestResponse], error)
	ListManifests(context.Context, *connect.Request[v1.ListManifestsRequest]) (*connect.Response[v1.ListManifestsResponse], error)
	GetManifest(context.Context, *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error)
	UpdateManifest(context.Context, *connect.Request[v1.UpdateManifestRequest]) (*connect.Response[v1.UpdateManifestResponse], error)
	DeleteManifest(context.Context, *connect.Request[v1.DeleteManifestRequest]) (*connect.Response[v1.DeleteManifestResponse], error)
}

// NewManifestAPIClient constructs a client for the admiral.manifest.v1.ManifestAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewManifestAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ManifestAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	manifestAPIMethods := v1.File_manifest_v1_manifest_proto.Services().ByName("ManifestAPI").Methods()
	return &manifestAPIClient{
		createManifest: connect.NewClient[v1.CreateManifestRequest, v1.CreateManifestResponse](
			httpClient,
			baseURL+ManifestAPICreateManifestProcedure,
			connect.WithSchema(manifestAPIMethods.ByName("CreateManifest")),
			connect.WithClientOptions(opts...),
		),
		listManifests: connect.NewClient[v1.ListManifestsRequest, v1.ListManifestsResponse](
			httpClient,
			baseURL+ManifestAPIListManifestsProcedure,
			connect.WithSchema(manifestAPIMethods.ByName("ListManifests")),
			connect.WithClientOptions(opts...),
		),
		getManifest: connect.NewClient[v1.GetManifestRequest, v1.GetManifestResponse](
			httpClient,
			baseURL+ManifestAPIGetManifestProcedure,
			connect.WithSchema(manifestAPIMethods.ByName("GetManifest")),
			connect.WithClientOptions(opts...),
		),
		updateManifest: connect.NewClient[v1.UpdateManifestRequest, v1.UpdateManifestResponse](
			httpClient,
			baseURL+ManifestAPIUpdateManifestProcedure,
			connect.WithSchema(manifestAPIMethods.ByName("UpdateManifest")),
			connect.WithClientOptions(opts...),
		),
		deleteManifest: connect.NewClient[v1.DeleteManifestRequest, v1.DeleteManifestResponse](
			httpClient,
			baseURL+ManifestAPIDeleteManifestProcedure,
			connect.WithSchema(manifestAPIMethods.ByName("DeleteManifest")),
			connect.WithClientOptions(opts...),
		),
	}
}

// manifestAPIClient implements ManifestAPIClient.
type manifestAPIClient struct {
	createManifest *connect.Client[v1.CreateManifestRequest, v1.CreateManifestResponse]
	listManifests  *connect.Client[v1.ListManifestsRequest, v1.ListManifestsResponse]
	getManifest    *connect.Client[v1.GetManifestRequest, v1.GetManifestResponse]
	updateManifest *connect.Client[v1.UpdateManifestRequest, v1.UpdateManifestResponse]
	deleteManifest *connect.Client[v1.DeleteManifestRequest, v1.DeleteManifestResponse]
}

// CreateManifest calls admiral.manifest.v1.ManifestAPI.CreateManifest.
func (c *manifestAPIClient) CreateManifest(ctx context.Context, req *connect.Request[v1.CreateManifestRequest]) (*connect.Response[v1.CreateManifestResponse], error) {
	return c.createManifest.CallUnary(ctx, req)
}

// ListManifests calls admiral.manifest.v1.ManifestAPI.ListManifests.
func (c *manifestAPIClient) ListManifests(ctx context.Context, req *connect.Request[v1.ListManifestsRequest]) (*connect.Response[v1.ListManifestsResponse], error) {
	return c.listManifests.CallUnary(ctx, req)
}

// GetManifest calls admiral.manifest.v1.ManifestAPI.GetManifest.
func (c *manifestAPIClient) GetManifest(ctx context.Context, req *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error) {
	return c.getManifest.CallUnary(ctx, req)
}

// UpdateManifest calls admiral.manifest.v1.ManifestAPI.UpdateManifest.
func (c *manifestAPIClient) UpdateManifest(ctx context.Context, req *connect.Request[v1.UpdateManifestRequest]) (*connect.Response[v1.UpdateManifestResponse], error) {
	return c.updateManifest.CallUnary(ctx, req)
}

// DeleteManifest calls admiral.manifest.v1.ManifestAPI.DeleteManifest.
func (c *manifestAPIClient) DeleteManifest(ctx context.Context, req *connect.Request[v1.DeleteManifestRequest]) (*connect.Response[v1.DeleteManifestResponse], error) {
	return c.deleteManifest.CallUnary(ctx, req)
}

// ManifestAPIHandler is an implementation of the admiral.manifest.v1.ManifestAPI service.
type ManifestAPIHandler interface {
	CreateManifest(context.Context, *connect.Request[v1.CreateManifestRequest]) (*connect.Response[v1.CreateManifestResponse], error)
	ListManifests(context.Context, *connect.Request[v1.ListManifestsRequest]) (*connect.Response[v1.ListManifestsResponse], error)
	GetManifest(context.Context, *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error)
	UpdateManifest(context.Context, *connect.Request[v1.UpdateManifestRequest]) (*connect.Response[v1.UpdateManifestResponse], error)
	DeleteManifest(context.Context, *connect.Request[v1.DeleteManifestRequest]) (*connect.Response[v1.DeleteManifestResponse], error)
}

// NewManifestAPIHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewManifestAPIHandler(svc ManifestAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	manifestAPIMethods := v1.File_manifest_v1_manifest_proto.Services().ByName("ManifestAPI").Methods()
	manifestAPICreateManifestHandler := connect.NewUnaryHandler(
		ManifestAPICreateManifestProcedure,
		svc.CreateManifest,
		connect.WithSchema(manifestAPIMethods.ByName("CreateManifest")),
		connect.WithHandlerOptions(opts...),
	)
	manifestAPIListManifestsHandler := connect.NewUnaryHandler(
		ManifestAPIListManifestsProcedure,
		svc.ListManifests,
		connect.WithSchema(manifestAPIMethods.ByName("ListManifests")),
		connect.WithHandlerOptions(opts...),
	)
	manifestAPIGetManifestHandler := connect.NewUnaryHandler(
		ManifestAPIGetManifestProcedure,
		svc.GetManifest,
		connect.WithSchema(manifestAPIMethods.ByName("GetManifest")),
		connect.WithHandlerOptions(opts...),
	)
	manifestAPIUpdateManifestHandler := connect.NewUnaryHandler(
		ManifestAPIUpdateManifestProcedure,
		svc.UpdateManifest,
		connect.WithSchema(manifestAPIMethods.ByName("UpdateManifest")),
		connect.WithHandlerOptions(opts...),
	)
	manifestAPIDeleteManifestHandler := connect.NewUnaryHandler(
		ManifestAPIDeleteManifestProcedure,
		svc.DeleteManifest,
		connect.WithSchema(manifestAPIMethods.ByName("DeleteManifest")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.manifest.v1.ManifestAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ManifestAPICreateManifestProcedure:
			manifestAPICreateManifestHandler.ServeHTTP(w, r)
		case ManifestAPIListManifestsProcedure:
			manifestAPIListManifestsHandler.ServeHTTP(w, r)
		case ManifestAPIGetManifestProcedure:
			manifestAPIGetManifestHandler.ServeHTTP(w, r)
		case ManifestAPIUpdateManifestProcedure:
			manifestAPIUpdateManifestHandler.ServeHTTP(w, r)
		case ManifestAPIDeleteManifestProcedure:
			manifestAPIDeleteManifestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedManifestAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedManifestAPIHandler struct{}

func (UnimplementedManifestAPIHandler) CreateManifest(context.Context, *connect.Request[v1.CreateManifestRequest]) (*connect.Response[v1.CreateManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.manifest.v1.ManifestAPI.CreateManifest is not implemented"))
}

func (UnimplementedManifestAPIHandler) ListManifests(context.Context, *connect.Request[v1.ListManifestsRequest]) (*connect.Response[v1.ListManifestsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.manifest.v1.ManifestAPI.ListManifests is not implemented"))
}

func (UnimplementedManifestAPIHandler) GetManifest(context.Context, *connect.Request[v1.GetManifestRequest]) (*connect.Response[v1.GetManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.manifest.v1.ManifestAPI.GetManifest is not implemented"))
}

func (UnimplementedManifestAPIHandler) UpdateManifest(context.Context, *connect.Request[v1.UpdateManifestRequest]) (*connect.Response[v1.UpdateManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.manifest.v1.ManifestAPI.UpdateManifest is not implemented"))
}

func (UnimplementedManifestAPIHandler) DeleteManifest(context.Context, *connect.Request[v1.DeleteManifestRequest]) (*connect.Response[v1.DeleteManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.manifest.v1.ManifestAPI.DeleteManifest is not implemented"))
}
