// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: revision/v1/revision.proto

package revisionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/admiral/api/revision/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RevisionAPIName is the fully-qualified name of the RevisionAPI service.
	RevisionAPIName = "admiral.revision.v1.RevisionAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RevisionAPICreateRevisionProcedure is the fully-qualified name of the RevisionAPI's
	// CreateRevision RPC.
	RevisionAPICreateRevisionProcedure = "/admiral.revision.v1.RevisionAPI/CreateRevision"
)

// RevisionAPIClient is a client for the admiral.revision.v1.RevisionAPI service.
type RevisionAPIClient interface {
	CreateRevision(context.Context, *connect.Request[v1.CreateRevisionRequest]) (*connect.Response[v1.CreateRevisionResponse], error)
}

// NewRevisionAPIClient constructs a client for the admiral.revision.v1.RevisionAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRevisionAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RevisionAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	revisionAPIMethods := v1.File_revision_v1_revision_proto.Services().ByName("RevisionAPI").Methods()
	return &revisionAPIClient{
		createRevision: connect.NewClient[v1.CreateRevisionRequest, v1.CreateRevisionResponse](
			httpClient,
			baseURL+RevisionAPICreateRevisionProcedure,
			connect.WithSchema(revisionAPIMethods.ByName("CreateRevision")),
			connect.WithClientOptions(opts...),
		),
	}
}

// revisionAPIClient implements RevisionAPIClient.
type revisionAPIClient struct {
	createRevision *connect.Client[v1.CreateRevisionRequest, v1.CreateRevisionResponse]
}

// CreateRevision calls admiral.revision.v1.RevisionAPI.CreateRevision.
func (c *revisionAPIClient) CreateRevision(ctx context.Context, req *connect.Request[v1.CreateRevisionRequest]) (*connect.Response[v1.CreateRevisionResponse], error) {
	return c.createRevision.CallUnary(ctx, req)
}

// RevisionAPIHandler is an implementation of the admiral.revision.v1.RevisionAPI service.
type RevisionAPIHandler interface {
	CreateRevision(context.Context, *connect.Request[v1.CreateRevisionRequest]) (*connect.Response[v1.CreateRevisionResponse], error)
}

// NewRevisionAPIHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRevisionAPIHandler(svc RevisionAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	revisionAPIMethods := v1.File_revision_v1_revision_proto.Services().ByName("RevisionAPI").Methods()
	revisionAPICreateRevisionHandler := connect.NewUnaryHandler(
		RevisionAPICreateRevisionProcedure,
		svc.CreateRevision,
		connect.WithSchema(revisionAPIMethods.ByName("CreateRevision")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.revision.v1.RevisionAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RevisionAPICreateRevisionProcedure:
			revisionAPICreateRevisionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRevisionAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedRevisionAPIHandler struct{}

func (UnimplementedRevisionAPIHandler) CreateRevision(context.Context, *connect.Request[v1.CreateRevisionRequest]) (*connect.Response[v1.CreateRevisionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.revision.v1.RevisionAPI.CreateRevision is not implemented"))
}
