syntax = "proto3";

package admiral.user.v1;

option go_package = "go.admiral.io/admiral/api/user/v1;userv1";

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";

service UserAPI {
  rpc GetMe(GetMeRequest) returns (GetMeResponse) {
    option (google.api.http) = {
      get: "/api/v1/user"
    };
  }

  rpc GetUser(GetUserRequest) returns (GetUserResponse) {
    option (google.api.http) = {
      get: "/api/v1/users/{id}"
    };
  }

  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {
    option (google.api.http) = {
      get : "/api/v1/users"
    };
  }
}

message User {
  string id = 1 [(buf.validate.field).string.uuid = true];
  string email = 2 [(buf.validate.field).string.email = true];
  bool email_verified = 3;
  string name = 4 [
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.max_len = 255
  ];
  string given_name = 5;
  string family_name = 6;
  string picture_url = 7;

  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
}

message GetMeRequest {}
message GetMeResponse {
  User user = 1;
}

message GetUserRequest {
  string id = 1 [(buf.validate.field).string.uuid = true];
}
message GetUserResponse {
  User user = 1;
}

message ListUsersRequest {
  string filter = 1;
  int32 page_size = 2;
  optional string page_token = 3;
}
message ListUsersResponse {
  repeated User users = 1;
  string next_page_token = 2;
}
