// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: environment/v1/environment.proto

package environmentv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Environment with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Environment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Environment with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EnvironmentMultiError, or
// nil if none found.
func (m *Environment) ValidateAll() error {
	return m.validate(true)
}

func (m *Environment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ApplicationId

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EnvironmentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EnvironmentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EnvironmentValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EnvironmentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EnvironmentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EnvironmentValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.ClusterId != nil {
		// no validation rules for ClusterId
	}

	if m.Namespace != nil {
		// no validation rules for Namespace
	}

	if len(errors) > 0 {
		return EnvironmentMultiError(errors)
	}

	return nil
}

// EnvironmentMultiError is an error wrapping multiple validation errors
// returned by Environment.ValidateAll() if the designated constraints aren't met.
type EnvironmentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EnvironmentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EnvironmentMultiError) AllErrors() []error { return m }

// EnvironmentValidationError is the validation error returned by
// Environment.Validate if the designated constraints aren't met.
type EnvironmentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnvironmentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnvironmentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnvironmentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnvironmentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnvironmentValidationError) ErrorName() string { return "EnvironmentValidationError" }

// Error satisfies the builtin error interface
func (e EnvironmentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnvironment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnvironmentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnvironmentValidationError{}

// Validate checks the field values on CreateEnvironmentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateEnvironmentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateEnvironmentRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateEnvironmentRequestMultiError, or nil if none found.
func (m *CreateEnvironmentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateEnvironmentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ApplicationId

	// no validation rules for Name

	if m.ClusterId != nil {
		// no validation rules for ClusterId
	}

	if m.Namespace != nil {
		// no validation rules for Namespace
	}

	if len(errors) > 0 {
		return CreateEnvironmentRequestMultiError(errors)
	}

	return nil
}

// CreateEnvironmentRequestMultiError is an error wrapping multiple validation
// errors returned by CreateEnvironmentRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateEnvironmentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateEnvironmentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateEnvironmentRequestMultiError) AllErrors() []error { return m }

// CreateEnvironmentRequestValidationError is the validation error returned by
// CreateEnvironmentRequest.Validate if the designated constraints aren't met.
type CreateEnvironmentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateEnvironmentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateEnvironmentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateEnvironmentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateEnvironmentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateEnvironmentRequestValidationError) ErrorName() string {
	return "CreateEnvironmentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateEnvironmentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateEnvironmentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateEnvironmentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateEnvironmentRequestValidationError{}

// Validate checks the field values on CreateEnvironmentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateEnvironmentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateEnvironmentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateEnvironmentResponseMultiError, or nil if none found.
func (m *CreateEnvironmentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateEnvironmentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEnvironment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateEnvironmentResponseValidationError{
					field:  "Environment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateEnvironmentResponseValidationError{
					field:  "Environment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEnvironment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateEnvironmentResponseValidationError{
				field:  "Environment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateEnvironmentResponseMultiError(errors)
	}

	return nil
}

// CreateEnvironmentResponseMultiError is an error wrapping multiple validation
// errors returned by CreateEnvironmentResponse.ValidateAll() if the
// designated constraints aren't met.
type CreateEnvironmentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateEnvironmentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateEnvironmentResponseMultiError) AllErrors() []error { return m }

// CreateEnvironmentResponseValidationError is the validation error returned by
// CreateEnvironmentResponse.Validate if the designated constraints aren't met.
type CreateEnvironmentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateEnvironmentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateEnvironmentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateEnvironmentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateEnvironmentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateEnvironmentResponseValidationError) ErrorName() string {
	return "CreateEnvironmentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateEnvironmentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateEnvironmentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateEnvironmentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateEnvironmentResponseValidationError{}

// Validate checks the field values on ListEnvironmentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListEnvironmentsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListEnvironmentsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListEnvironmentsRequestMultiError, or nil if none found.
func (m *ListEnvironmentsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListEnvironmentsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Filter

	// no validation rules for PageSize

	if m.PageToken != nil {
		// no validation rules for PageToken
	}

	if len(errors) > 0 {
		return ListEnvironmentsRequestMultiError(errors)
	}

	return nil
}

// ListEnvironmentsRequestMultiError is an error wrapping multiple validation
// errors returned by ListEnvironmentsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListEnvironmentsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListEnvironmentsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListEnvironmentsRequestMultiError) AllErrors() []error { return m }

// ListEnvironmentsRequestValidationError is the validation error returned by
// ListEnvironmentsRequest.Validate if the designated constraints aren't met.
type ListEnvironmentsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListEnvironmentsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListEnvironmentsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListEnvironmentsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListEnvironmentsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListEnvironmentsRequestValidationError) ErrorName() string {
	return "ListEnvironmentsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListEnvironmentsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListEnvironmentsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListEnvironmentsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListEnvironmentsRequestValidationError{}

// Validate checks the field values on ListEnvironmentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListEnvironmentsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListEnvironmentsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListEnvironmentsResponseMultiError, or nil if none found.
func (m *ListEnvironmentsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListEnvironmentsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetEnvironments() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListEnvironmentsResponseValidationError{
						field:  fmt.Sprintf("Environments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListEnvironmentsResponseValidationError{
						field:  fmt.Sprintf("Environments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListEnvironmentsResponseValidationError{
					field:  fmt.Sprintf("Environments[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListEnvironmentsResponseMultiError(errors)
	}

	return nil
}

// ListEnvironmentsResponseMultiError is an error wrapping multiple validation
// errors returned by ListEnvironmentsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListEnvironmentsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListEnvironmentsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListEnvironmentsResponseMultiError) AllErrors() []error { return m }

// ListEnvironmentsResponseValidationError is the validation error returned by
// ListEnvironmentsResponse.Validate if the designated constraints aren't met.
type ListEnvironmentsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListEnvironmentsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListEnvironmentsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListEnvironmentsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListEnvironmentsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListEnvironmentsResponseValidationError) ErrorName() string {
	return "ListEnvironmentsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListEnvironmentsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListEnvironmentsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListEnvironmentsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListEnvironmentsResponseValidationError{}

// Validate checks the field values on GetEnvironmentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEnvironmentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEnvironmentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEnvironmentRequestMultiError, or nil if none found.
func (m *GetEnvironmentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEnvironmentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetEnvironmentRequestMultiError(errors)
	}

	return nil
}

// GetEnvironmentRequestMultiError is an error wrapping multiple validation
// errors returned by GetEnvironmentRequest.ValidateAll() if the designated
// constraints aren't met.
type GetEnvironmentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEnvironmentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEnvironmentRequestMultiError) AllErrors() []error { return m }

// GetEnvironmentRequestValidationError is the validation error returned by
// GetEnvironmentRequest.Validate if the designated constraints aren't met.
type GetEnvironmentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEnvironmentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEnvironmentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEnvironmentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEnvironmentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEnvironmentRequestValidationError) ErrorName() string {
	return "GetEnvironmentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetEnvironmentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEnvironmentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEnvironmentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEnvironmentRequestValidationError{}

// Validate checks the field values on GetEnvironmentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEnvironmentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEnvironmentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEnvironmentResponseMultiError, or nil if none found.
func (m *GetEnvironmentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEnvironmentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEnvironment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetEnvironmentResponseValidationError{
					field:  "Environment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetEnvironmentResponseValidationError{
					field:  "Environment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEnvironment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetEnvironmentResponseValidationError{
				field:  "Environment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetEnvironmentResponseMultiError(errors)
	}

	return nil
}

// GetEnvironmentResponseMultiError is an error wrapping multiple validation
// errors returned by GetEnvironmentResponse.ValidateAll() if the designated
// constraints aren't met.
type GetEnvironmentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEnvironmentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEnvironmentResponseMultiError) AllErrors() []error { return m }

// GetEnvironmentResponseValidationError is the validation error returned by
// GetEnvironmentResponse.Validate if the designated constraints aren't met.
type GetEnvironmentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEnvironmentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEnvironmentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEnvironmentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEnvironmentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEnvironmentResponseValidationError) ErrorName() string {
	return "GetEnvironmentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetEnvironmentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEnvironmentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEnvironmentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEnvironmentResponseValidationError{}

// Validate checks the field values on UpdateEnvironmentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateEnvironmentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateEnvironmentRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateEnvironmentRequestMultiError, or nil if none found.
func (m *UpdateEnvironmentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateEnvironmentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEnvironment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateEnvironmentRequestValidationError{
					field:  "Environment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateEnvironmentRequestValidationError{
					field:  "Environment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEnvironment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateEnvironmentRequestValidationError{
				field:  "Environment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateEnvironmentRequestMultiError(errors)
	}

	return nil
}

// UpdateEnvironmentRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateEnvironmentRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateEnvironmentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateEnvironmentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateEnvironmentRequestMultiError) AllErrors() []error { return m }

// UpdateEnvironmentRequestValidationError is the validation error returned by
// UpdateEnvironmentRequest.Validate if the designated constraints aren't met.
type UpdateEnvironmentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateEnvironmentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateEnvironmentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateEnvironmentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateEnvironmentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateEnvironmentRequestValidationError) ErrorName() string {
	return "UpdateEnvironmentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateEnvironmentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateEnvironmentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateEnvironmentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateEnvironmentRequestValidationError{}

// Validate checks the field values on UpdateEnvironmentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateEnvironmentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateEnvironmentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateEnvironmentResponseMultiError, or nil if none found.
func (m *UpdateEnvironmentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateEnvironmentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEnvironment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateEnvironmentResponseValidationError{
					field:  "Environment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateEnvironmentResponseValidationError{
					field:  "Environment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEnvironment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateEnvironmentResponseValidationError{
				field:  "Environment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateEnvironmentResponseMultiError(errors)
	}

	return nil
}

// UpdateEnvironmentResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateEnvironmentResponse.ValidateAll() if the
// designated constraints aren't met.
type UpdateEnvironmentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateEnvironmentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateEnvironmentResponseMultiError) AllErrors() []error { return m }

// UpdateEnvironmentResponseValidationError is the validation error returned by
// UpdateEnvironmentResponse.Validate if the designated constraints aren't met.
type UpdateEnvironmentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateEnvironmentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateEnvironmentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateEnvironmentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateEnvironmentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateEnvironmentResponseValidationError) ErrorName() string {
	return "UpdateEnvironmentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateEnvironmentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateEnvironmentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateEnvironmentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateEnvironmentResponseValidationError{}

// Validate checks the field values on DeleteEnvironmentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteEnvironmentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteEnvironmentRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteEnvironmentRequestMultiError, or nil if none found.
func (m *DeleteEnvironmentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteEnvironmentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteEnvironmentRequestMultiError(errors)
	}

	return nil
}

// DeleteEnvironmentRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteEnvironmentRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteEnvironmentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteEnvironmentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteEnvironmentRequestMultiError) AllErrors() []error { return m }

// DeleteEnvironmentRequestValidationError is the validation error returned by
// DeleteEnvironmentRequest.Validate if the designated constraints aren't met.
type DeleteEnvironmentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteEnvironmentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteEnvironmentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteEnvironmentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteEnvironmentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteEnvironmentRequestValidationError) ErrorName() string {
	return "DeleteEnvironmentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteEnvironmentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteEnvironmentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteEnvironmentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteEnvironmentRequestValidationError{}

// Validate checks the field values on DeleteEnvironmentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteEnvironmentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteEnvironmentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteEnvironmentResponseMultiError, or nil if none found.
func (m *DeleteEnvironmentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteEnvironmentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteEnvironmentResponseMultiError(errors)
	}

	return nil
}

// DeleteEnvironmentResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteEnvironmentResponse.ValidateAll() if the
// designated constraints aren't met.
type DeleteEnvironmentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteEnvironmentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteEnvironmentResponseMultiError) AllErrors() []error { return m }

// DeleteEnvironmentResponseValidationError is the validation error returned by
// DeleteEnvironmentResponse.Validate if the designated constraints aren't met.
type DeleteEnvironmentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteEnvironmentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteEnvironmentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteEnvironmentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteEnvironmentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteEnvironmentResponseValidationError) ErrorName() string {
	return "DeleteEnvironmentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteEnvironmentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteEnvironmentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteEnvironmentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteEnvironmentResponseValidationError{}
