// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: environment/v1/environment.proto

package environmentv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ClusterId     *string                `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3,oneof" json:"cluster_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     *string                `protobuf:"bytes,5,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_environment_v1_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{0}
}

func (x *Environment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Environment) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Environment) GetClusterId() string {
	if x != nil && x.ClusterId != nil {
		return *x.ClusterId
	}
	return ""
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Environment) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *Environment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Environment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ClusterId     *string                `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3,oneof" json:"cluster_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     *string                `protobuf:"bytes,4,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentRequest) Reset() {
	*x = CreateEnvironmentRequest{}
	mi := &file_environment_v1_environment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentRequest) ProtoMessage() {}

func (x *CreateEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEnvironmentRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CreateEnvironmentRequest) GetClusterId() string {
	if x != nil && x.ClusterId != nil {
		return *x.ClusterId
	}
	return ""
}

func (x *CreateEnvironmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEnvironmentRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type CreateEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   *Environment           `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentResponse) Reset() {
	*x = CreateEnvironmentResponse{}
	mi := &file_environment_v1_environment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentResponse) ProtoMessage() {}

func (x *CreateEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEnvironmentResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

type ListEnvironmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnvironmentsRequest) Reset() {
	*x = ListEnvironmentsRequest{}
	mi := &file_environment_v1_environment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnvironmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvironmentsRequest) ProtoMessage() {}

func (x *ListEnvironmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvironmentsRequest.ProtoReflect.Descriptor instead.
func (*ListEnvironmentsRequest) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{3}
}

func (x *ListEnvironmentsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListEnvironmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEnvironmentsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListEnvironmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environments  []*Environment         `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnvironmentsResponse) Reset() {
	*x = ListEnvironmentsResponse{}
	mi := &file_environment_v1_environment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnvironmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvironmentsResponse) ProtoMessage() {}

func (x *ListEnvironmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvironmentsResponse.ProtoReflect.Descriptor instead.
func (*ListEnvironmentsResponse) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{4}
}

func (x *ListEnvironmentsResponse) GetEnvironments() []*Environment {
	if x != nil {
		return x.Environments
	}
	return nil
}

func (x *ListEnvironmentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentRequest) Reset() {
	*x = GetEnvironmentRequest{}
	mi := &file_environment_v1_environment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentRequest) ProtoMessage() {}

func (x *GetEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{5}
}

func (x *GetEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   *Environment           `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentResponse) Reset() {
	*x = GetEnvironmentResponse{}
	mi := &file_environment_v1_environment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentResponse) ProtoMessage() {}

func (x *GetEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*GetEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{6}
}

func (x *GetEnvironmentResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

type UpdateEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   *Environment           `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnvironmentRequest) Reset() {
	*x = UpdateEnvironmentRequest{}
	mi := &file_environment_v1_environment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvironmentRequest) ProtoMessage() {}

func (x *UpdateEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEnvironmentRequest) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

type UpdateEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   *Environment           `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnvironmentResponse) Reset() {
	*x = UpdateEnvironmentResponse{}
	mi := &file_environment_v1_environment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvironmentResponse) ProtoMessage() {}

func (x *UpdateEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateEnvironmentResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

type DeleteEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentRequest) Reset() {
	*x = DeleteEnvironmentRequest{}
	mi := &file_environment_v1_environment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentRequest) ProtoMessage() {}

func (x *DeleteEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentResponse) Reset() {
	*x = DeleteEnvironmentResponse{}
	mi := &file_environment_v1_environment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentResponse) ProtoMessage() {}

func (x *DeleteEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environment_v1_environment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_environment_v1_environment_proto_rawDescGZIP(), []int{10}
}

var File_environment_v1_environment_proto protoreflect.FileDescriptor

const file_environment_v1_environment_proto_rawDesc = "" +
	"\n" +
	" environment/v1/environment.proto\x12\x16admiral.environment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xd2\x02\n" +
	"\vEnvironment\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12/\n" +
	"\x0eapplication_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x12\"\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tH\x00R\tclusterId\x88\x01\x01\x12\x1e\n" +
	"\x04name\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12!\n" +
	"\tnamespace\x18\x05 \x01(\tH\x01R\tnamespace\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\r\n" +
	"\v_cluster_idB\f\n" +
	"\n" +
	"_namespace\"\xcf\x01\n" +
	"\x18CreateEnvironmentRequest\x12/\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x12\"\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tH\x00R\tclusterId\x88\x01\x01\x12\x1e\n" +
	"\x04name\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12!\n" +
	"\tnamespace\x18\x04 \x01(\tH\x01R\tnamespace\x88\x01\x01B\r\n" +
	"\v_cluster_idB\f\n" +
	"\n" +
	"_namespace\"b\n" +
	"\x19CreateEnvironmentResponse\x12E\n" +
	"\venvironment\x18\x01 \x01(\v2#.admiral.environment.v1.EnvironmentR\venvironment\"\x81\x01\n" +
	"\x17ListEnvironmentsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x00R\tpageToken\x88\x01\x01B\r\n" +
	"\v_page_token\"\x8b\x01\n" +
	"\x18ListEnvironmentsResponse\x12G\n" +
	"\fenvironments\x18\x01 \x03(\v2#.admiral.environment.v1.EnvironmentR\fenvironments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"1\n" +
	"\x15GetEnvironmentRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"_\n" +
	"\x16GetEnvironmentResponse\x12E\n" +
	"\venvironment\x18\x01 \x01(\v2#.admiral.environment.v1.EnvironmentR\venvironment\"a\n" +
	"\x18UpdateEnvironmentRequest\x12E\n" +
	"\venvironment\x18\x01 \x01(\v2#.admiral.environment.v1.EnvironmentR\venvironment\"b\n" +
	"\x19UpdateEnvironmentResponse\x12E\n" +
	"\venvironment\x18\x01 \x01(\v2#.admiral.environment.v1.EnvironmentR\venvironment\"4\n" +
	"\x18DeleteEnvironmentRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x1b\n" +
	"\x19DeleteEnvironmentResponse2\xa2\x06\n" +
	"\x0eEnvironmentAPI\x12\x99\x01\n" +
	"\x11CreateEnvironment\x120.admiral.environment.v1.CreateEnvironmentRequest\x1a1.admiral.environment.v1.CreateEnvironmentResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/environments\x12\x93\x01\n" +
	"\x10ListEnvironments\x12/.admiral.environment.v1.ListEnvironmentsRequest\x1a0.admiral.environment.v1.ListEnvironmentsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/environments\x12\x92\x01\n" +
	"\x0eGetEnvironment\x12-.admiral.environment.v1.GetEnvironmentRequest\x1a..admiral.environment.v1.GetEnvironmentResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/environments/{id}\x12\xaa\x01\n" +
	"\x11UpdateEnvironment\x120.admiral.environment.v1.UpdateEnvironmentRequest\x1a1.admiral.environment.v1.UpdateEnvironmentResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\x1a%/api/v1/environments/{environment.id}\x12\x9b\x01\n" +
	"\x11DeleteEnvironment\x120.admiral.environment.v1.DeleteEnvironmentRequest\x1a1.admiral.environment.v1.DeleteEnvironmentResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/v1/environments/{id}B\xe0\x01\n" +
	"\x1acom.admiral.environment.v1B\x10EnvironmentProtoP\x01Z6go.admiral.io/admiral/api/environment/v1;environmentv1\xa2\x02\x03AEX\xaa\x02\x16Admiral.Environment.V1\xca\x02\x16Admiral\\Environment\\V1\xe2\x02\"Admiral\\Environment\\V1\\GPBMetadata\xea\x02\x18Admiral::Environment::V1b\x06proto3"

var (
	file_environment_v1_environment_proto_rawDescOnce sync.Once
	file_environment_v1_environment_proto_rawDescData []byte
)

func file_environment_v1_environment_proto_rawDescGZIP() []byte {
	file_environment_v1_environment_proto_rawDescOnce.Do(func() {
		file_environment_v1_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_environment_v1_environment_proto_rawDesc), len(file_environment_v1_environment_proto_rawDesc)))
	})
	return file_environment_v1_environment_proto_rawDescData
}

var file_environment_v1_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_environment_v1_environment_proto_goTypes = []any{
	(*Environment)(nil),               // 0: admiral.environment.v1.Environment
	(*CreateEnvironmentRequest)(nil),  // 1: admiral.environment.v1.CreateEnvironmentRequest
	(*CreateEnvironmentResponse)(nil), // 2: admiral.environment.v1.CreateEnvironmentResponse
	(*ListEnvironmentsRequest)(nil),   // 3: admiral.environment.v1.ListEnvironmentsRequest
	(*ListEnvironmentsResponse)(nil),  // 4: admiral.environment.v1.ListEnvironmentsResponse
	(*GetEnvironmentRequest)(nil),     // 5: admiral.environment.v1.GetEnvironmentRequest
	(*GetEnvironmentResponse)(nil),    // 6: admiral.environment.v1.GetEnvironmentResponse
	(*UpdateEnvironmentRequest)(nil),  // 7: admiral.environment.v1.UpdateEnvironmentRequest
	(*UpdateEnvironmentResponse)(nil), // 8: admiral.environment.v1.UpdateEnvironmentResponse
	(*DeleteEnvironmentRequest)(nil),  // 9: admiral.environment.v1.DeleteEnvironmentRequest
	(*DeleteEnvironmentResponse)(nil), // 10: admiral.environment.v1.DeleteEnvironmentResponse
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_environment_v1_environment_proto_depIdxs = []int32{
	11, // 0: admiral.environment.v1.Environment.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: admiral.environment.v1.Environment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: admiral.environment.v1.CreateEnvironmentResponse.environment:type_name -> admiral.environment.v1.Environment
	0,  // 3: admiral.environment.v1.ListEnvironmentsResponse.environments:type_name -> admiral.environment.v1.Environment
	0,  // 4: admiral.environment.v1.GetEnvironmentResponse.environment:type_name -> admiral.environment.v1.Environment
	0,  // 5: admiral.environment.v1.UpdateEnvironmentRequest.environment:type_name -> admiral.environment.v1.Environment
	0,  // 6: admiral.environment.v1.UpdateEnvironmentResponse.environment:type_name -> admiral.environment.v1.Environment
	1,  // 7: admiral.environment.v1.EnvironmentAPI.CreateEnvironment:input_type -> admiral.environment.v1.CreateEnvironmentRequest
	3,  // 8: admiral.environment.v1.EnvironmentAPI.ListEnvironments:input_type -> admiral.environment.v1.ListEnvironmentsRequest
	5,  // 9: admiral.environment.v1.EnvironmentAPI.GetEnvironment:input_type -> admiral.environment.v1.GetEnvironmentRequest
	7,  // 10: admiral.environment.v1.EnvironmentAPI.UpdateEnvironment:input_type -> admiral.environment.v1.UpdateEnvironmentRequest
	9,  // 11: admiral.environment.v1.EnvironmentAPI.DeleteEnvironment:input_type -> admiral.environment.v1.DeleteEnvironmentRequest
	2,  // 12: admiral.environment.v1.EnvironmentAPI.CreateEnvironment:output_type -> admiral.environment.v1.CreateEnvironmentResponse
	4,  // 13: admiral.environment.v1.EnvironmentAPI.ListEnvironments:output_type -> admiral.environment.v1.ListEnvironmentsResponse
	6,  // 14: admiral.environment.v1.EnvironmentAPI.GetEnvironment:output_type -> admiral.environment.v1.GetEnvironmentResponse
	8,  // 15: admiral.environment.v1.EnvironmentAPI.UpdateEnvironment:output_type -> admiral.environment.v1.UpdateEnvironmentResponse
	10, // 16: admiral.environment.v1.EnvironmentAPI.DeleteEnvironment:output_type -> admiral.environment.v1.DeleteEnvironmentResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_environment_v1_environment_proto_init() }
func file_environment_v1_environment_proto_init() {
	if File_environment_v1_environment_proto != nil {
		return
	}
	file_environment_v1_environment_proto_msgTypes[0].OneofWrappers = []any{}
	file_environment_v1_environment_proto_msgTypes[1].OneofWrappers = []any{}
	file_environment_v1_environment_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_environment_v1_environment_proto_rawDesc), len(file_environment_v1_environment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_environment_v1_environment_proto_goTypes,
		DependencyIndexes: file_environment_v1_environment_proto_depIdxs,
		MessageInfos:      file_environment_v1_environment_proto_msgTypes,
	}.Build()
	File_environment_v1_environment_proto = out.File
	file_environment_v1_environment_proto_goTypes = nil
	file_environment_v1_environment_proto_depIdxs = nil
}
