// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: variable/v1/variable.proto

package variablev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/admiral/api/variable/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// VariableAPIName is the fully-qualified name of the VariableAPI service.
	VariableAPIName = "admiral.variable.v1.VariableAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VariableAPICreateVariableProcedure is the fully-qualified name of the VariableAPI's
	// CreateVariable RPC.
	VariableAPICreateVariableProcedure = "/admiral.variable.v1.VariableAPI/CreateVariable"
	// VariableAPIListVariablesProcedure is the fully-qualified name of the VariableAPI's ListVariables
	// RPC.
	VariableAPIListVariablesProcedure = "/admiral.variable.v1.VariableAPI/ListVariables"
	// VariableAPIGetVariableProcedure is the fully-qualified name of the VariableAPI's GetVariable RPC.
	VariableAPIGetVariableProcedure = "/admiral.variable.v1.VariableAPI/GetVariable"
	// VariableAPIUpdateVariableProcedure is the fully-qualified name of the VariableAPI's
	// UpdateVariable RPC.
	VariableAPIUpdateVariableProcedure = "/admiral.variable.v1.VariableAPI/UpdateVariable"
	// VariableAPIDeleteVariableProcedure is the fully-qualified name of the VariableAPI's
	// DeleteVariable RPC.
	VariableAPIDeleteVariableProcedure = "/admiral.variable.v1.VariableAPI/DeleteVariable"
)

// VariableAPIClient is a client for the admiral.variable.v1.VariableAPI service.
type VariableAPIClient interface {
	CreateVariable(context.Context, *connect.Request[v1.CreateVariableRequest]) (*connect.Response[v1.CreateVariableResponse], error)
	ListVariables(context.Context, *connect.Request[v1.ListVariablesRequest]) (*connect.Response[v1.ListVariablesResponse], error)
	GetVariable(context.Context, *connect.Request[v1.GetVariableRequest]) (*connect.Response[v1.GetVariableResponse], error)
	UpdateVariable(context.Context, *connect.Request[v1.UpdateVariableRequest]) (*connect.Response[v1.UpdateVariableResponse], error)
	DeleteVariable(context.Context, *connect.Request[v1.DeleteVariableRequest]) (*connect.Response[v1.DeleteVariableResponse], error)
}

// NewVariableAPIClient constructs a client for the admiral.variable.v1.VariableAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVariableAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VariableAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	variableAPIMethods := v1.File_variable_v1_variable_proto.Services().ByName("VariableAPI").Methods()
	return &variableAPIClient{
		createVariable: connect.NewClient[v1.CreateVariableRequest, v1.CreateVariableResponse](
			httpClient,
			baseURL+VariableAPICreateVariableProcedure,
			connect.WithSchema(variableAPIMethods.ByName("CreateVariable")),
			connect.WithClientOptions(opts...),
		),
		listVariables: connect.NewClient[v1.ListVariablesRequest, v1.ListVariablesResponse](
			httpClient,
			baseURL+VariableAPIListVariablesProcedure,
			connect.WithSchema(variableAPIMethods.ByName("ListVariables")),
			connect.WithClientOptions(opts...),
		),
		getVariable: connect.NewClient[v1.GetVariableRequest, v1.GetVariableResponse](
			httpClient,
			baseURL+VariableAPIGetVariableProcedure,
			connect.WithSchema(variableAPIMethods.ByName("GetVariable")),
			connect.WithClientOptions(opts...),
		),
		updateVariable: connect.NewClient[v1.UpdateVariableRequest, v1.UpdateVariableResponse](
			httpClient,
			baseURL+VariableAPIUpdateVariableProcedure,
			connect.WithSchema(variableAPIMethods.ByName("UpdateVariable")),
			connect.WithClientOptions(opts...),
		),
		deleteVariable: connect.NewClient[v1.DeleteVariableRequest, v1.DeleteVariableResponse](
			httpClient,
			baseURL+VariableAPIDeleteVariableProcedure,
			connect.WithSchema(variableAPIMethods.ByName("DeleteVariable")),
			connect.WithClientOptions(opts...),
		),
	}
}

// variableAPIClient implements VariableAPIClient.
type variableAPIClient struct {
	createVariable *connect.Client[v1.CreateVariableRequest, v1.CreateVariableResponse]
	listVariables  *connect.Client[v1.ListVariablesRequest, v1.ListVariablesResponse]
	getVariable    *connect.Client[v1.GetVariableRequest, v1.GetVariableResponse]
	updateVariable *connect.Client[v1.UpdateVariableRequest, v1.UpdateVariableResponse]
	deleteVariable *connect.Client[v1.DeleteVariableRequest, v1.DeleteVariableResponse]
}

// CreateVariable calls admiral.variable.v1.VariableAPI.CreateVariable.
func (c *variableAPIClient) CreateVariable(ctx context.Context, req *connect.Request[v1.CreateVariableRequest]) (*connect.Response[v1.CreateVariableResponse], error) {
	return c.createVariable.CallUnary(ctx, req)
}

// ListVariables calls admiral.variable.v1.VariableAPI.ListVariables.
func (c *variableAPIClient) ListVariables(ctx context.Context, req *connect.Request[v1.ListVariablesRequest]) (*connect.Response[v1.ListVariablesResponse], error) {
	return c.listVariables.CallUnary(ctx, req)
}

// GetVariable calls admiral.variable.v1.VariableAPI.GetVariable.
func (c *variableAPIClient) GetVariable(ctx context.Context, req *connect.Request[v1.GetVariableRequest]) (*connect.Response[v1.GetVariableResponse], error) {
	return c.getVariable.CallUnary(ctx, req)
}

// UpdateVariable calls admiral.variable.v1.VariableAPI.UpdateVariable.
func (c *variableAPIClient) UpdateVariable(ctx context.Context, req *connect.Request[v1.UpdateVariableRequest]) (*connect.Response[v1.UpdateVariableResponse], error) {
	return c.updateVariable.CallUnary(ctx, req)
}

// DeleteVariable calls admiral.variable.v1.VariableAPI.DeleteVariable.
func (c *variableAPIClient) DeleteVariable(ctx context.Context, req *connect.Request[v1.DeleteVariableRequest]) (*connect.Response[v1.DeleteVariableResponse], error) {
	return c.deleteVariable.CallUnary(ctx, req)
}

// VariableAPIHandler is an implementation of the admiral.variable.v1.VariableAPI service.
type VariableAPIHandler interface {
	CreateVariable(context.Context, *connect.Request[v1.CreateVariableRequest]) (*connect.Response[v1.CreateVariableResponse], error)
	ListVariables(context.Context, *connect.Request[v1.ListVariablesRequest]) (*connect.Response[v1.ListVariablesResponse], error)
	GetVariable(context.Context, *connect.Request[v1.GetVariableRequest]) (*connect.Response[v1.GetVariableResponse], error)
	UpdateVariable(context.Context, *connect.Request[v1.UpdateVariableRequest]) (*connect.Response[v1.UpdateVariableResponse], error)
	DeleteVariable(context.Context, *connect.Request[v1.DeleteVariableRequest]) (*connect.Response[v1.DeleteVariableResponse], error)
}

// NewVariableAPIHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVariableAPIHandler(svc VariableAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	variableAPIMethods := v1.File_variable_v1_variable_proto.Services().ByName("VariableAPI").Methods()
	variableAPICreateVariableHandler := connect.NewUnaryHandler(
		VariableAPICreateVariableProcedure,
		svc.CreateVariable,
		connect.WithSchema(variableAPIMethods.ByName("CreateVariable")),
		connect.WithHandlerOptions(opts...),
	)
	variableAPIListVariablesHandler := connect.NewUnaryHandler(
		VariableAPIListVariablesProcedure,
		svc.ListVariables,
		connect.WithSchema(variableAPIMethods.ByName("ListVariables")),
		connect.WithHandlerOptions(opts...),
	)
	variableAPIGetVariableHandler := connect.NewUnaryHandler(
		VariableAPIGetVariableProcedure,
		svc.GetVariable,
		connect.WithSchema(variableAPIMethods.ByName("GetVariable")),
		connect.WithHandlerOptions(opts...),
	)
	variableAPIUpdateVariableHandler := connect.NewUnaryHandler(
		VariableAPIUpdateVariableProcedure,
		svc.UpdateVariable,
		connect.WithSchema(variableAPIMethods.ByName("UpdateVariable")),
		connect.WithHandlerOptions(opts...),
	)
	variableAPIDeleteVariableHandler := connect.NewUnaryHandler(
		VariableAPIDeleteVariableProcedure,
		svc.DeleteVariable,
		connect.WithSchema(variableAPIMethods.ByName("DeleteVariable")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.variable.v1.VariableAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VariableAPICreateVariableProcedure:
			variableAPICreateVariableHandler.ServeHTTP(w, r)
		case VariableAPIListVariablesProcedure:
			variableAPIListVariablesHandler.ServeHTTP(w, r)
		case VariableAPIGetVariableProcedure:
			variableAPIGetVariableHandler.ServeHTTP(w, r)
		case VariableAPIUpdateVariableProcedure:
			variableAPIUpdateVariableHandler.ServeHTTP(w, r)
		case VariableAPIDeleteVariableProcedure:
			variableAPIDeleteVariableHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVariableAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedVariableAPIHandler struct{}

func (UnimplementedVariableAPIHandler) CreateVariable(context.Context, *connect.Request[v1.CreateVariableRequest]) (*connect.Response[v1.CreateVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.variable.v1.VariableAPI.CreateVariable is not implemented"))
}

func (UnimplementedVariableAPIHandler) ListVariables(context.Context, *connect.Request[v1.ListVariablesRequest]) (*connect.Response[v1.ListVariablesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.variable.v1.VariableAPI.ListVariables is not implemented"))
}

func (UnimplementedVariableAPIHandler) GetVariable(context.Context, *connect.Request[v1.GetVariableRequest]) (*connect.Response[v1.GetVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.variable.v1.VariableAPI.GetVariable is not implemented"))
}

func (UnimplementedVariableAPIHandler) UpdateVariable(context.Context, *connect.Request[v1.UpdateVariableRequest]) (*connect.Response[v1.UpdateVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.variable.v1.VariableAPI.UpdateVariable is not implemented"))
}

func (UnimplementedVariableAPIHandler) DeleteVariable(context.Context, *connect.Request[v1.DeleteVariableRequest]) (*connect.Response[v1.DeleteVariableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.variable.v1.VariableAPI.DeleteVariable is not implemented"))
}
