// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: variable/v1/variable.proto

package variablev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId *string                `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3,oneof" json:"application_id,omitempty"`
	EnvironmentId *string                `protobuf:"bytes,3,opt,name=environment_id,json=environmentId,proto3,oneof" json:"environment_id,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsSensitive   bool                   `protobuf:"varint,7,opt,name=is_sensitive,json=isSensitive,proto3" json:"is_sensitive,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_variable_v1_variable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{0}
}

func (x *Variable) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Variable) GetApplicationId() string {
	if x != nil && x.ApplicationId != nil {
		return *x.ApplicationId
	}
	return ""
}

func (x *Variable) GetEnvironmentId() string {
	if x != nil && x.EnvironmentId != nil {
		return *x.EnvironmentId
	}
	return ""
}

func (x *Variable) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Variable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Variable) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Variable) GetIsSensitive() bool {
	if x != nil {
		return x.IsSensitive
	}
	return false
}

func (x *Variable) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Variable) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId *string                `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3,oneof" json:"application_id,omitempty"`
	EnvironmentId *string                `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3,oneof" json:"environment_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsSensitive   bool                   `protobuf:"varint,6,opt,name=is_sensitive,json=isSensitive,proto3" json:"is_sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVariableRequest) Reset() {
	*x = CreateVariableRequest{}
	mi := &file_variable_v1_variable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariableRequest) ProtoMessage() {}

func (x *CreateVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariableRequest.ProtoReflect.Descriptor instead.
func (*CreateVariableRequest) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVariableRequest) GetApplicationId() string {
	if x != nil && x.ApplicationId != nil {
		return *x.ApplicationId
	}
	return ""
}

func (x *CreateVariableRequest) GetEnvironmentId() string {
	if x != nil && x.EnvironmentId != nil {
		return *x.EnvironmentId
	}
	return ""
}

func (x *CreateVariableRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateVariableRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateVariableRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateVariableRequest) GetIsSensitive() bool {
	if x != nil {
		return x.IsSensitive
	}
	return false
}

type CreateVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *Variable              `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVariableResponse) Reset() {
	*x = CreateVariableResponse{}
	mi := &file_variable_v1_variable_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariableResponse) ProtoMessage() {}

func (x *CreateVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariableResponse.ProtoReflect.Descriptor instead.
func (*CreateVariableResponse) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVariableResponse) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type ListVariablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Effective     bool                   `protobuf:"varint,2,opt,name=effective,proto3" json:"effective,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVariablesRequest) Reset() {
	*x = ListVariablesRequest{}
	mi := &file_variable_v1_variable_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVariablesRequest) ProtoMessage() {}

func (x *ListVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVariablesRequest.ProtoReflect.Descriptor instead.
func (*ListVariablesRequest) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{3}
}

func (x *ListVariablesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListVariablesRequest) GetEffective() bool {
	if x != nil {
		return x.Effective
	}
	return false
}

func (x *ListVariablesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVariablesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListVariablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variables     []*Variable            `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVariablesResponse) Reset() {
	*x = ListVariablesResponse{}
	mi := &file_variable_v1_variable_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVariablesResponse) ProtoMessage() {}

func (x *ListVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVariablesResponse.ProtoReflect.Descriptor instead.
func (*ListVariablesResponse) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{4}
}

func (x *ListVariablesResponse) GetVariables() []*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ListVariablesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariableRequest) Reset() {
	*x = GetVariableRequest{}
	mi := &file_variable_v1_variable_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableRequest) ProtoMessage() {}

func (x *GetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableRequest.ProtoReflect.Descriptor instead.
func (*GetVariableRequest) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{5}
}

func (x *GetVariableRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *Variable              `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVariableResponse) Reset() {
	*x = GetVariableResponse{}
	mi := &file_variable_v1_variable_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableResponse) ProtoMessage() {}

func (x *GetVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableResponse.ProtoReflect.Descriptor instead.
func (*GetVariableResponse) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{6}
}

func (x *GetVariableResponse) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type UpdateVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *Variable              `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVariableRequest) Reset() {
	*x = UpdateVariableRequest{}
	mi := &file_variable_v1_variable_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariableRequest) ProtoMessage() {}

func (x *UpdateVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariableRequest.ProtoReflect.Descriptor instead.
func (*UpdateVariableRequest) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateVariableRequest) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type UpdateVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      *Variable              `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVariableResponse) Reset() {
	*x = UpdateVariableResponse{}
	mi := &file_variable_v1_variable_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariableResponse) ProtoMessage() {}

func (x *UpdateVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariableResponse.ProtoReflect.Descriptor instead.
func (*UpdateVariableResponse) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateVariableResponse) GetVariable() *Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type DeleteVariableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVariableRequest) Reset() {
	*x = DeleteVariableRequest{}
	mi := &file_variable_v1_variable_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVariableRequest) ProtoMessage() {}

func (x *DeleteVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVariableRequest.ProtoReflect.Descriptor instead.
func (*DeleteVariableRequest) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteVariableRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteVariableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVariableResponse) Reset() {
	*x = DeleteVariableResponse{}
	mi := &file_variable_v1_variable_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVariableResponse) ProtoMessage() {}

func (x *DeleteVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_variable_v1_variable_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVariableResponse.ProtoReflect.Descriptor instead.
func (*DeleteVariableResponse) Descriptor() ([]byte, []int) {
	return file_variable_v1_variable_proto_rawDescGZIP(), []int{10}
}

var File_variable_v1_variable_proto protoreflect.FileDescriptor

const file_variable_v1_variable_proto_rawDesc = "" +
	"\n" +
	"\x1avariable/v1/variable.proto\x12\x13admiral.variable.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xf0\x03\n" +
	"\bVariable\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x124\n" +
	"\x0eapplication_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\rapplicationId\x88\x01\x01\x124\n" +
	"\x0eenvironment_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x01R\renvironmentId\x88\x01\x01\x12I\n" +
	"\x03key\x18\x04 \x01(\tB7\xbaH4r2\x10\x01\x18\xff\x012+^[a-zA-Z0-9_]([-a-zA-Z0-9_]*[a-zA-Z0-9_])?$R\x03key\x12\x1d\n" +
	"\x05value\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05value\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x02R\vdescription\x88\x01\x01\x12!\n" +
	"\fis_sensitive\x18\a \x01(\bR\visSensitive\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x11\n" +
	"\x0f_application_idB\x11\n" +
	"\x0f_environment_idB\x0e\n" +
	"\f_description\"\xed\x02\n" +
	"\x15CreateVariableRequest\x124\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\rapplicationId\x88\x01\x01\x124\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x01R\renvironmentId\x88\x01\x01\x12I\n" +
	"\x03key\x18\x03 \x01(\tB7\xbaH4r2\x10\x01\x18\xff\x012+^[a-zA-Z0-9_]([-a-zA-Z0-9_]*[a-zA-Z0-9_])?$R\x03key\x12\x1d\n" +
	"\x05value\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05value\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x02R\vdescription\x88\x01\x01\x12!\n" +
	"\fis_sensitive\x18\x06 \x01(\bR\visSensitiveB\x11\n" +
	"\x0f_application_idB\x11\n" +
	"\x0f_environment_idB\x0e\n" +
	"\f_description\"S\n" +
	"\x16CreateVariableResponse\x129\n" +
	"\bvariable\x18\x01 \x01(\v2\x1d.admiral.variable.v1.VariableR\bvariable\"\x9c\x01\n" +
	"\x14ListVariablesRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x1c\n" +
	"\teffective\x18\x02 \x01(\bR\teffective\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tH\x00R\tpageToken\x88\x01\x01B\r\n" +
	"\v_page_token\"|\n" +
	"\x15ListVariablesResponse\x12;\n" +
	"\tvariables\x18\x01 \x03(\v2\x1d.admiral.variable.v1.VariableR\tvariables\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\".\n" +
	"\x12GetVariableRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"P\n" +
	"\x13GetVariableResponse\x129\n" +
	"\bvariable\x18\x01 \x01(\v2\x1d.admiral.variable.v1.VariableR\bvariable\"R\n" +
	"\x15UpdateVariableRequest\x129\n" +
	"\bvariable\x18\x01 \x01(\v2\x1d.admiral.variable.v1.VariableR\bvariable\"S\n" +
	"\x16UpdateVariableResponse\x129\n" +
	"\bvariable\x18\x01 \x01(\v2\x1d.admiral.variable.v1.VariableR\bvariable\"1\n" +
	"\x15DeleteVariableRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x18\n" +
	"\x16DeleteVariableResponse2\xc2\x05\n" +
	"\vVariableAPI\x12\x87\x01\n" +
	"\x0eCreateVariable\x12*.admiral.variable.v1.CreateVariableRequest\x1a+.admiral.variable.v1.CreateVariableResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/variables\x12\x81\x01\n" +
	"\rListVariables\x12).admiral.variable.v1.ListVariablesRequest\x1a*.admiral.variable.v1.ListVariablesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/variables\x12\x80\x01\n" +
	"\vGetVariable\x12'.admiral.variable.v1.GetVariableRequest\x1a(.admiral.variable.v1.GetVariableResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/variables/{id}\x12\x95\x01\n" +
	"\x0eUpdateVariable\x12*.admiral.variable.v1.UpdateVariableRequest\x1a+.admiral.variable.v1.UpdateVariableResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/api/v1/variables/{variable.id}\x12\x89\x01\n" +
	"\x0eDeleteVariable\x12*.admiral.variable.v1.DeleteVariableRequest\x1a+.admiral.variable.v1.DeleteVariableResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/variables/{id}B\xc8\x01\n" +
	"\x17com.admiral.variable.v1B\rVariableProtoP\x01Z0go.admiral.io/admiral/api/variable/v1;variablev1\xa2\x02\x03AVX\xaa\x02\x13Admiral.Variable.V1\xca\x02\x13Admiral\\Variable\\V1\xe2\x02\x1fAdmiral\\Variable\\V1\\GPBMetadata\xea\x02\x15Admiral::Variable::V1b\x06proto3"

var (
	file_variable_v1_variable_proto_rawDescOnce sync.Once
	file_variable_v1_variable_proto_rawDescData []byte
)

func file_variable_v1_variable_proto_rawDescGZIP() []byte {
	file_variable_v1_variable_proto_rawDescOnce.Do(func() {
		file_variable_v1_variable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_variable_v1_variable_proto_rawDesc), len(file_variable_v1_variable_proto_rawDesc)))
	})
	return file_variable_v1_variable_proto_rawDescData
}

var file_variable_v1_variable_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_variable_v1_variable_proto_goTypes = []any{
	(*Variable)(nil),               // 0: admiral.variable.v1.Variable
	(*CreateVariableRequest)(nil),  // 1: admiral.variable.v1.CreateVariableRequest
	(*CreateVariableResponse)(nil), // 2: admiral.variable.v1.CreateVariableResponse
	(*ListVariablesRequest)(nil),   // 3: admiral.variable.v1.ListVariablesRequest
	(*ListVariablesResponse)(nil),  // 4: admiral.variable.v1.ListVariablesResponse
	(*GetVariableRequest)(nil),     // 5: admiral.variable.v1.GetVariableRequest
	(*GetVariableResponse)(nil),    // 6: admiral.variable.v1.GetVariableResponse
	(*UpdateVariableRequest)(nil),  // 7: admiral.variable.v1.UpdateVariableRequest
	(*UpdateVariableResponse)(nil), // 8: admiral.variable.v1.UpdateVariableResponse
	(*DeleteVariableRequest)(nil),  // 9: admiral.variable.v1.DeleteVariableRequest
	(*DeleteVariableResponse)(nil), // 10: admiral.variable.v1.DeleteVariableResponse
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
}
var file_variable_v1_variable_proto_depIdxs = []int32{
	11, // 0: admiral.variable.v1.Variable.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: admiral.variable.v1.Variable.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: admiral.variable.v1.CreateVariableResponse.variable:type_name -> admiral.variable.v1.Variable
	0,  // 3: admiral.variable.v1.ListVariablesResponse.variables:type_name -> admiral.variable.v1.Variable
	0,  // 4: admiral.variable.v1.GetVariableResponse.variable:type_name -> admiral.variable.v1.Variable
	0,  // 5: admiral.variable.v1.UpdateVariableRequest.variable:type_name -> admiral.variable.v1.Variable
	0,  // 6: admiral.variable.v1.UpdateVariableResponse.variable:type_name -> admiral.variable.v1.Variable
	1,  // 7: admiral.variable.v1.VariableAPI.CreateVariable:input_type -> admiral.variable.v1.CreateVariableRequest
	3,  // 8: admiral.variable.v1.VariableAPI.ListVariables:input_type -> admiral.variable.v1.ListVariablesRequest
	5,  // 9: admiral.variable.v1.VariableAPI.GetVariable:input_type -> admiral.variable.v1.GetVariableRequest
	7,  // 10: admiral.variable.v1.VariableAPI.UpdateVariable:input_type -> admiral.variable.v1.UpdateVariableRequest
	9,  // 11: admiral.variable.v1.VariableAPI.DeleteVariable:input_type -> admiral.variable.v1.DeleteVariableRequest
	2,  // 12: admiral.variable.v1.VariableAPI.CreateVariable:output_type -> admiral.variable.v1.CreateVariableResponse
	4,  // 13: admiral.variable.v1.VariableAPI.ListVariables:output_type -> admiral.variable.v1.ListVariablesResponse
	6,  // 14: admiral.variable.v1.VariableAPI.GetVariable:output_type -> admiral.variable.v1.GetVariableResponse
	8,  // 15: admiral.variable.v1.VariableAPI.UpdateVariable:output_type -> admiral.variable.v1.UpdateVariableResponse
	10, // 16: admiral.variable.v1.VariableAPI.DeleteVariable:output_type -> admiral.variable.v1.DeleteVariableResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_variable_v1_variable_proto_init() }
func file_variable_v1_variable_proto_init() {
	if File_variable_v1_variable_proto != nil {
		return
	}
	file_variable_v1_variable_proto_msgTypes[0].OneofWrappers = []any{}
	file_variable_v1_variable_proto_msgTypes[1].OneofWrappers = []any{}
	file_variable_v1_variable_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_variable_v1_variable_proto_rawDesc), len(file_variable_v1_variable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_variable_v1_variable_proto_goTypes,
		DependencyIndexes: file_variable_v1_variable_proto_depIdxs,
		MessageInfos:      file_variable_v1_variable_proto_msgTypes,
	}.Build()
	File_variable_v1_variable_proto = out.File
	file_variable_v1_variable_proto_goTypes = nil
	file_variable_v1_variable_proto_depIdxs = nil
}
