// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: variable/v1/variable.proto

package variablev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Variable with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Variable) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Variable with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VariableMultiError, or nil
// if none found.
func (m *Variable) ValidateAll() error {
	return m.validate(true)
}

func (m *Variable) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Key

	// no validation rules for Value

	// no validation rules for IsSensitive

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VariableValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VariableValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VariableValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, VariableValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, VariableValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VariableValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.ApplicationId != nil {
		// no validation rules for ApplicationId
	}

	if m.EnvironmentId != nil {
		// no validation rules for EnvironmentId
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if len(errors) > 0 {
		return VariableMultiError(errors)
	}

	return nil
}

// VariableMultiError is an error wrapping multiple validation errors returned
// by Variable.ValidateAll() if the designated constraints aren't met.
type VariableMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VariableMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VariableMultiError) AllErrors() []error { return m }

// VariableValidationError is the validation error returned by
// Variable.Validate if the designated constraints aren't met.
type VariableValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VariableValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VariableValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VariableValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VariableValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VariableValidationError) ErrorName() string { return "VariableValidationError" }

// Error satisfies the builtin error interface
func (e VariableValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVariable.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VariableValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VariableValidationError{}

// Validate checks the field values on CreateVariableRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateVariableRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateVariableRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateVariableRequestMultiError, or nil if none found.
func (m *CreateVariableRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateVariableRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	// no validation rules for Value

	// no validation rules for IsSensitive

	if m.ApplicationId != nil {
		// no validation rules for ApplicationId
	}

	if m.EnvironmentId != nil {
		// no validation rules for EnvironmentId
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if len(errors) > 0 {
		return CreateVariableRequestMultiError(errors)
	}

	return nil
}

// CreateVariableRequestMultiError is an error wrapping multiple validation
// errors returned by CreateVariableRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateVariableRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateVariableRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateVariableRequestMultiError) AllErrors() []error { return m }

// CreateVariableRequestValidationError is the validation error returned by
// CreateVariableRequest.Validate if the designated constraints aren't met.
type CreateVariableRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateVariableRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateVariableRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateVariableRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateVariableRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateVariableRequestValidationError) ErrorName() string {
	return "CreateVariableRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateVariableRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateVariableRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateVariableRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateVariableRequestValidationError{}

// Validate checks the field values on CreateVariableResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateVariableResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateVariableResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateVariableResponseMultiError, or nil if none found.
func (m *CreateVariableResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateVariableResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetVariable()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateVariableResponseValidationError{
					field:  "Variable",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateVariableResponseValidationError{
					field:  "Variable",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVariable()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateVariableResponseValidationError{
				field:  "Variable",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateVariableResponseMultiError(errors)
	}

	return nil
}

// CreateVariableResponseMultiError is an error wrapping multiple validation
// errors returned by CreateVariableResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateVariableResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateVariableResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateVariableResponseMultiError) AllErrors() []error { return m }

// CreateVariableResponseValidationError is the validation error returned by
// CreateVariableResponse.Validate if the designated constraints aren't met.
type CreateVariableResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateVariableResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateVariableResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateVariableResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateVariableResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateVariableResponseValidationError) ErrorName() string {
	return "CreateVariableResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateVariableResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateVariableResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateVariableResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateVariableResponseValidationError{}

// Validate checks the field values on ListVariablesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListVariablesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListVariablesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListVariablesRequestMultiError, or nil if none found.
func (m *ListVariablesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListVariablesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Filter

	// no validation rules for Effective

	// no validation rules for PageSize

	if m.PageToken != nil {
		// no validation rules for PageToken
	}

	if len(errors) > 0 {
		return ListVariablesRequestMultiError(errors)
	}

	return nil
}

// ListVariablesRequestMultiError is an error wrapping multiple validation
// errors returned by ListVariablesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListVariablesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListVariablesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListVariablesRequestMultiError) AllErrors() []error { return m }

// ListVariablesRequestValidationError is the validation error returned by
// ListVariablesRequest.Validate if the designated constraints aren't met.
type ListVariablesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListVariablesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListVariablesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListVariablesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListVariablesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListVariablesRequestValidationError) ErrorName() string {
	return "ListVariablesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListVariablesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListVariablesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListVariablesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListVariablesRequestValidationError{}

// Validate checks the field values on ListVariablesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListVariablesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListVariablesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListVariablesResponseMultiError, or nil if none found.
func (m *ListVariablesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListVariablesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetVariables() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListVariablesResponseValidationError{
						field:  fmt.Sprintf("Variables[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListVariablesResponseValidationError{
						field:  fmt.Sprintf("Variables[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListVariablesResponseValidationError{
					field:  fmt.Sprintf("Variables[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListVariablesResponseMultiError(errors)
	}

	return nil
}

// ListVariablesResponseMultiError is an error wrapping multiple validation
// errors returned by ListVariablesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListVariablesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListVariablesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListVariablesResponseMultiError) AllErrors() []error { return m }

// ListVariablesResponseValidationError is the validation error returned by
// ListVariablesResponse.Validate if the designated constraints aren't met.
type ListVariablesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListVariablesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListVariablesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListVariablesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListVariablesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListVariablesResponseValidationError) ErrorName() string {
	return "ListVariablesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListVariablesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListVariablesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListVariablesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListVariablesResponseValidationError{}

// Validate checks the field values on GetVariableRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetVariableRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVariableRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetVariableRequestMultiError, or nil if none found.
func (m *GetVariableRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVariableRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetVariableRequestMultiError(errors)
	}

	return nil
}

// GetVariableRequestMultiError is an error wrapping multiple validation errors
// returned by GetVariableRequest.ValidateAll() if the designated constraints
// aren't met.
type GetVariableRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVariableRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVariableRequestMultiError) AllErrors() []error { return m }

// GetVariableRequestValidationError is the validation error returned by
// GetVariableRequest.Validate if the designated constraints aren't met.
type GetVariableRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVariableRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVariableRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVariableRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVariableRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVariableRequestValidationError) ErrorName() string {
	return "GetVariableRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetVariableRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVariableRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVariableRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVariableRequestValidationError{}

// Validate checks the field values on GetVariableResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetVariableResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetVariableResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetVariableResponseMultiError, or nil if none found.
func (m *GetVariableResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetVariableResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetVariable()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetVariableResponseValidationError{
					field:  "Variable",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetVariableResponseValidationError{
					field:  "Variable",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVariable()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetVariableResponseValidationError{
				field:  "Variable",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetVariableResponseMultiError(errors)
	}

	return nil
}

// GetVariableResponseMultiError is an error wrapping multiple validation
// errors returned by GetVariableResponse.ValidateAll() if the designated
// constraints aren't met.
type GetVariableResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetVariableResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetVariableResponseMultiError) AllErrors() []error { return m }

// GetVariableResponseValidationError is the validation error returned by
// GetVariableResponse.Validate if the designated constraints aren't met.
type GetVariableResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetVariableResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetVariableResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetVariableResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetVariableResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetVariableResponseValidationError) ErrorName() string {
	return "GetVariableResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetVariableResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetVariableResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetVariableResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetVariableResponseValidationError{}

// Validate checks the field values on UpdateVariableRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateVariableRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateVariableRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateVariableRequestMultiError, or nil if none found.
func (m *UpdateVariableRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateVariableRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetVariable()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateVariableRequestValidationError{
					field:  "Variable",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateVariableRequestValidationError{
					field:  "Variable",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVariable()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateVariableRequestValidationError{
				field:  "Variable",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateVariableRequestMultiError(errors)
	}

	return nil
}

// UpdateVariableRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateVariableRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateVariableRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateVariableRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateVariableRequestMultiError) AllErrors() []error { return m }

// UpdateVariableRequestValidationError is the validation error returned by
// UpdateVariableRequest.Validate if the designated constraints aren't met.
type UpdateVariableRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateVariableRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateVariableRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateVariableRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateVariableRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateVariableRequestValidationError) ErrorName() string {
	return "UpdateVariableRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateVariableRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateVariableRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateVariableRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateVariableRequestValidationError{}

// Validate checks the field values on UpdateVariableResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateVariableResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateVariableResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateVariableResponseMultiError, or nil if none found.
func (m *UpdateVariableResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateVariableResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetVariable()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateVariableResponseValidationError{
					field:  "Variable",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateVariableResponseValidationError{
					field:  "Variable",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVariable()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateVariableResponseValidationError{
				field:  "Variable",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateVariableResponseMultiError(errors)
	}

	return nil
}

// UpdateVariableResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateVariableResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateVariableResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateVariableResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateVariableResponseMultiError) AllErrors() []error { return m }

// UpdateVariableResponseValidationError is the validation error returned by
// UpdateVariableResponse.Validate if the designated constraints aren't met.
type UpdateVariableResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateVariableResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateVariableResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateVariableResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateVariableResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateVariableResponseValidationError) ErrorName() string {
	return "UpdateVariableResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateVariableResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateVariableResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateVariableResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateVariableResponseValidationError{}

// Validate checks the field values on DeleteVariableRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteVariableRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteVariableRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteVariableRequestMultiError, or nil if none found.
func (m *DeleteVariableRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteVariableRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteVariableRequestMultiError(errors)
	}

	return nil
}

// DeleteVariableRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteVariableRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteVariableRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteVariableRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteVariableRequestMultiError) AllErrors() []error { return m }

// DeleteVariableRequestValidationError is the validation error returned by
// DeleteVariableRequest.Validate if the designated constraints aren't met.
type DeleteVariableRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteVariableRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteVariableRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteVariableRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteVariableRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteVariableRequestValidationError) ErrorName() string {
	return "DeleteVariableRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteVariableRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteVariableRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteVariableRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteVariableRequestValidationError{}

// Validate checks the field values on DeleteVariableResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteVariableResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteVariableResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteVariableResponseMultiError, or nil if none found.
func (m *DeleteVariableResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteVariableResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteVariableResponseMultiError(errors)
	}

	return nil
}

// DeleteVariableResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteVariableResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteVariableResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteVariableResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteVariableResponseMultiError) AllErrors() []error { return m }

// DeleteVariableResponseValidationError is the validation error returned by
// DeleteVariableResponse.Validate if the designated constraints aren't met.
type DeleteVariableResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteVariableResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteVariableResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteVariableResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteVariableResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteVariableResponseValidationError) ErrorName() string {
	return "DeleteVariableResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteVariableResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteVariableResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteVariableResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteVariableResponseValidationError{}
